/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.1 at 7/5/2021 7:01:28 AM.
 * 
 * @copyright copyright(c) 2018 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup LARK_BF
 * @{
 */
#ifndef __ADI_LARK_BF_WDT_H__
#define __ADI_LARK_BF_WDT_H__

/*============= D E F I N E S ==============*/
#define REG_WDT_LD_VAL_ADDR          0x40006800
#define BF_WDT_LD_VAL_INFO           0x40006800, 0x00001000

#define REG_WDT_CURR_VAL_ADDR        0x40006804
#define BF_WDT_CURR_VAL_INFO         0x40006804, 0x00001000

#define REG_WDT_CTRL_ADDR            0x40006808
#define BF_WDT_TO_BEHAVE_INFO        0x40006808, 0x00000101
#define BF_WDT_PRE_SCALER_INFO       0x40006808, 0x00000202
#define BF_WDT_EN_INFO               0x40006808, 0x00000105
#define BF_WDT_MODE_INFO             0x40006808, 0x00000106
#define BF_SPARE_INFO                0x40006808, 0x00000107
#define BF_WDT_CLKDIV2_INFO          0x40006808, 0x00000108
#define BF_WDT_MIN_LD_EN_INFO        0x40006808, 0x00000109
#define BF_WDT_INT_EN_INFO           0x40006808, 0x0000010A

#define REG_WDT_CLR_ADDR             0x4000680C
#define BF_WDT_CLR_INFO              0x4000680C, 0x00001000

#define REG_WDT_STATUS_ADDR          0x40006818
#define BF_WDT_IRQ_INFO              0x40006818, 0x00000100
#define BF_WDT_CLR_WR_BUSY_INFO      0x40006818, 0x00000101
#define BF_WDT_LD_VAL_WR_BUSY_INFO   0x40006818, 0x00000102
#define BF_WDT_CFG_WR_BUSY_INFO      0x40006818, 0x00000103
#define BF_WDT_LOCK_INFO             0x40006818, 0x00000104
#define BF_WDT_RST_CTRL_WR_BUSY_INFO 0x40006818, 0x00000105
#define BF_WDT_MIN_LD_WR_BUSY_INFO   0x40006818, 0x00000106

#define REG_WDT_MIN_LD_ADDR          0x4000681C
#define BF_WDT_MIN_LD_INFO           0x4000681C, 0x00001000

#endif /* __ADI_LARK_BF_WDT_H__ */
/*! @} */
