/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.1 at 7/5/2021 7:01:28 AM.
 * 
 * @copyright copyright(c) 2018 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup LARK_BF
 * @{
 */
#ifndef __ADI_LARK_BF_FIFO_SRAM_H__
#define __ADI_LARK_BF_FIFO_SRAM_H__

/*============= D E F I N E S ==============*/
#define FFSRAM0_CFG                      0x40010000
#define FFSRAM1_CFG                      0x40020000
#define FFSRAM2_CFG                      0x40030000

#define REG_FF0_PORT_ADDR(inst)          ((inst) + 0x00000000)
#define BF_FIFO0_PORT_INFO(inst)         ((inst) + 0x00000000), 0x00002000

#define REG_FF0_INIT_ADDR(inst)          ((inst) + 0x00000004)
#define BF_FIFO0_BASE_ADDR_INFO(inst)    ((inst) + 0x00000004), 0x00000800
#define BF_FIFO0_LEN_INFO(inst)          ((inst) + 0x00000004), 0x00000808
#define BF_FIFO0_WIDTH_INFO(inst)        ((inst) + 0x00000004), 0x00000110

#define REG_FF0_CSR_ADDR(inst)           ((inst) + 0x00000008)
#define BF_FIFO0_USED_INFO(inst)         ((inst) + 0x00000008), 0x00001000
#define BF_FIFO0_FLUSH_INFO(inst)        ((inst) + 0x00000008), 0x00000110
#define BF_FIFO0_EN_INFO(inst)           ((inst) + 0x00000008), 0x00000111
#define BF_FIFO0_DLINE_EN_INFO(inst)     ((inst) + 0x00000008), 0x00000112

#define REG_FF0_PTR_ADDR(inst)           ((inst) + 0x0000000C)
#define BF_FIFO0_WR_PTR_INFO(inst)       ((inst) + 0x0000000C), 0x00001000
#define BF_FIFO0_RD_PTR_INFO(inst)       ((inst) + 0x0000000C), 0x00001010

#define REG_FF0_INT_ADDR(inst)           ((inst) + 0x00000010)
#define BF_FIFO0_EMPTY_STATUS_INFO(inst) ((inst) + 0x00000010), 0x00000100
#define BF_FIFO0_FULL_STATUS_INFO(inst)  ((inst) + 0x00000010), 0x00000101
#define BF_FIFO0_ALME_STATUS_INFO(inst)  ((inst) + 0x00000010), 0x00000102
#define BF_FIFO0_ALMF_STATUS_INFO(inst)  ((inst) + 0x00000010), 0x00000103
#define BF_FIFO0_UD_STATUS_INFO(inst)    ((inst) + 0x00000010), 0x00000104
#define BF_FIFO0_OV_STATUS_INFO(inst)    ((inst) + 0x00000010), 0x00000105
#define BF_FIFO0_EMPTY_EN_INFO(inst)     ((inst) + 0x00000010), 0x00000108
#define BF_FIFO0_FULL_EN_INFO(inst)      ((inst) + 0x00000010), 0x00000109
#define BF_FIFO0_ALME_EN_INFO(inst)      ((inst) + 0x00000010), 0x0000010A
#define BF_FIFO0_ALMF_EN_INFO(inst)      ((inst) + 0x00000010), 0x0000010B
#define BF_FIFO0_UD_EN_INFO(inst)        ((inst) + 0x00000010), 0x0000010C
#define BF_FIFO0_OV_EN_INFO(inst)        ((inst) + 0x00000010), 0x0000010D
#define BF_FIFO0_EMPTY_CLR_INFO(inst)    ((inst) + 0x00000010), 0x00000110
#define BF_FIFO0_FULL_CLR_INFO(inst)     ((inst) + 0x00000010), 0x00000111
#define BF_FIFO0_ALME_CLR_INFO(inst)     ((inst) + 0x00000010), 0x00000112
#define BF_FIFO0_ALMF_CLR_INFO(inst)     ((inst) + 0x00000010), 0x00000113
#define BF_FIFO0_UD_CLR_INFO(inst)       ((inst) + 0x00000010), 0x00000114
#define BF_FIFO0_OV_CLR_INFO(inst)       ((inst) + 0x00000010), 0x00000115

#define REG_FF0_TH_ADDR(inst)            ((inst) + 0x00000014)
#define BF_FIFO0_ALMF_LEN_INFO(inst)     ((inst) + 0x00000014), 0x00000800
#define BF_FIFO0_ALME_LEN_INFO(inst)     ((inst) + 0x00000014), 0x00000808
#define BF_FIFO0_DLINE_LEN_INFO(inst)    ((inst) + 0x00000014), 0x00001010

#define REG_FF1_PORT_ADDR(inst)          ((inst) + 0x00000020)
#define BF_FIFO1_PORT_INFO(inst)         ((inst) + 0x00000020), 0x00002000

#define REG_FF1_INIT_ADDR(inst)          ((inst) + 0x00000024)
#define BF_FIFO1_BASE_ADDR_INFO(inst)    ((inst) + 0x00000024), 0x00000800
#define BF_FIFO1_LEN_INFO(inst)          ((inst) + 0x00000024), 0x00000808
#define BF_FIFO1_WIDTH_INFO(inst)        ((inst) + 0x00000024), 0x00000110

#define REG_FF1_CSR_ADDR(inst)           ((inst) + 0x00000028)
#define BF_FIFO1_USED_INFO(inst)         ((inst) + 0x00000028), 0x00001000
#define BF_FIFO1_FLUSH_INFO(inst)        ((inst) + 0x00000028), 0x00000110
#define BF_FIFO1_EN_INFO(inst)           ((inst) + 0x00000028), 0x00000111
#define BF_FIFO1_DLINE_EN_INFO(inst)     ((inst) + 0x00000028), 0x00000112

#define REG_FF1_PTR_ADDR(inst)           ((inst) + 0x0000002C)
#define BF_FIFO1_WR_PTR_INFO(inst)       ((inst) + 0x0000002C), 0x00001000
#define BF_FIFO1_RD_PTR_INFO(inst)       ((inst) + 0x0000002C), 0x00001010

#define REG_FF1_INT_ADDR(inst)           ((inst) + 0x00000030)
#define BF_FIFO1_EMPTY_STATUS_INFO(inst) ((inst) + 0x00000030), 0x00000100
#define BF_FIFO1_FULL_STATUS_INFO(inst)  ((inst) + 0x00000030), 0x00000101
#define BF_FIFO1_ALME_STATUS_INFO(inst)  ((inst) + 0x00000030), 0x00000102
#define BF_FIFO1_ALMF_STATUS_INFO(inst)  ((inst) + 0x00000030), 0x00000103
#define BF_FIFO1_UD_STATUS_INFO(inst)    ((inst) + 0x00000030), 0x00000104
#define BF_FIFO1_OV_STATUS_INFO(inst)    ((inst) + 0x00000030), 0x00000105
#define BF_FIFO1_EMPTY_EN_INFO(inst)     ((inst) + 0x00000030), 0x00000108
#define BF_FIFO1_FULL_EN_INFO(inst)      ((inst) + 0x00000030), 0x00000109
#define BF_FIFO1_ALME_EN_INFO(inst)      ((inst) + 0x00000030), 0x0000010A
#define BF_FIFO1_ALMF_EN_INFO(inst)      ((inst) + 0x00000030), 0x0000010B
#define BF_FIFO1_UD_EN_INFO(inst)        ((inst) + 0x00000030), 0x0000010C
#define BF_FIFO1_OV_EN_INFO(inst)        ((inst) + 0x00000030), 0x0000010D
#define BF_FIFO1_EMPTY_CLR_INFO(inst)    ((inst) + 0x00000030), 0x00000110
#define BF_FIFO1_FULL_CLR_INFO(inst)     ((inst) + 0x00000030), 0x00000111
#define BF_FIFO1_ALME_CLR_INFO(inst)     ((inst) + 0x00000030), 0x00000112
#define BF_FIFO1_ALMF_CLR_INFO(inst)     ((inst) + 0x00000030), 0x00000113
#define BF_FIFO1_UD_CLR_INFO(inst)       ((inst) + 0x00000030), 0x00000114
#define BF_FIFO1_OV_CLR_INFO(inst)       ((inst) + 0x00000030), 0x00000115

#define REG_FF1_TH_ADDR(inst)            ((inst) + 0x00000034)
#define BF_FIFO1_ALMF_LEN_INFO(inst)     ((inst) + 0x00000034), 0x00000800
#define BF_FIFO1_ALME_LEN_INFO(inst)     ((inst) + 0x00000034), 0x00000808
#define BF_FIFO1_DLINE_LEN_INFO(inst)    ((inst) + 0x00000034), 0x00001010

#define REG_FF2_PORT_ADDR(inst)          ((inst) + 0x00000040)
#define BF_FIFO2_PORT_INFO(inst)         ((inst) + 0x00000040), 0x00002000

#define REG_FF2_INIT_ADDR(inst)          ((inst) + 0x00000044)
#define BF_FIFO2_BASE_ADDR_INFO(inst)    ((inst) + 0x00000044), 0x00000800
#define BF_FIFO2_LEN_INFO(inst)          ((inst) + 0x00000044), 0x00000808
#define BF_FIFO2_WIDTH_INFO(inst)        ((inst) + 0x00000044), 0x00000110

#define REG_FF2_CSR_ADDR(inst)           ((inst) + 0x00000048)
#define BF_FIFO2_USED_INFO(inst)         ((inst) + 0x00000048), 0x00001000
#define BF_FIFO2_FLUSH_INFO(inst)        ((inst) + 0x00000048), 0x00000110
#define BF_FIFO2_EN_INFO(inst)           ((inst) + 0x00000048), 0x00000111
#define BF_FIFO2_DLINE_EN_INFO(inst)     ((inst) + 0x00000048), 0x00000112

#define REG_FF2_PTR_ADDR(inst)           ((inst) + 0x0000004C)
#define BF_FIFO2_WR_PTR_INFO(inst)       ((inst) + 0x0000004C), 0x00001000
#define BF_FIFO2_RD_PTR_INFO(inst)       ((inst) + 0x0000004C), 0x00001010

#define REG_FF2_INT_ADDR(inst)           ((inst) + 0x00000050)
#define BF_FIFO2_EMPTY_STATUS_INFO(inst) ((inst) + 0x00000050), 0x00000100
#define BF_FIFO2_FULL_STATUS_INFO(inst)  ((inst) + 0x00000050), 0x00000101
#define BF_FIFO2_ALME_STATUS_INFO(inst)  ((inst) + 0x00000050), 0x00000102
#define BF_FIFO2_ALMF_STATUS_INFO(inst)  ((inst) + 0x00000050), 0x00000103
#define BF_FIFO2_UD_STATUS_INFO(inst)    ((inst) + 0x00000050), 0x00000104
#define BF_FIFO2_OV_STATUS_INFO(inst)    ((inst) + 0x00000050), 0x00000105
#define BF_FIFO2_EMPTY_EN_INFO(inst)     ((inst) + 0x00000050), 0x00000108
#define BF_FIFO2_FULL_EN_INFO(inst)      ((inst) + 0x00000050), 0x00000109
#define BF_FIFO2_ALME_EN_INFO(inst)      ((inst) + 0x00000050), 0x0000010A
#define BF_FIFO2_ALMF_EN_INFO(inst)      ((inst) + 0x00000050), 0x0000010B
#define BF_FIFO2_UD_EN_INFO(inst)        ((inst) + 0x00000050), 0x0000010C
#define BF_FIFO2_OV_EN_INFO(inst)        ((inst) + 0x00000050), 0x0000010D
#define BF_FIFO2_EMPTY_CLR_INFO(inst)    ((inst) + 0x00000050), 0x00000110
#define BF_FIFO2_FULL_CLR_INFO(inst)     ((inst) + 0x00000050), 0x00000111
#define BF_FIFO2_ALME_CLR_INFO(inst)     ((inst) + 0x00000050), 0x00000112
#define BF_FIFO2_ALMF_CLR_INFO(inst)     ((inst) + 0x00000050), 0x00000113
#define BF_FIFO2_UD_CLR_INFO(inst)       ((inst) + 0x00000050), 0x00000114
#define BF_FIFO2_OV_CLR_INFO(inst)       ((inst) + 0x00000050), 0x00000115

#define REG_FF2_TH_ADDR(inst)            ((inst) + 0x00000054)
#define BF_FIFO2_ALMF_LEN_INFO(inst)     ((inst) + 0x00000054), 0x00000800
#define BF_FIFO2_ALME_LEN_INFO(inst)     ((inst) + 0x00000054), 0x00000808
#define BF_FIFO2_DLINE_LEN_INFO(inst)    ((inst) + 0x00000054), 0x00001010

#define REG_FF3_PORT_ADDR(inst)          ((inst) + 0x00000060)
#define BF_FIFO3_PORT_INFO(inst)         ((inst) + 0x00000060), 0x00002000

#define REG_FF3_INIT_ADDR(inst)          ((inst) + 0x00000064)
#define BF_FIFO3_BASE_ADDR_INFO(inst)    ((inst) + 0x00000064), 0x00000800
#define BF_FIFO3_LEN_INFO(inst)          ((inst) + 0x00000064), 0x00000808
#define BF_FIFO3_WIDTH_INFO(inst)        ((inst) + 0x00000064), 0x00000110

#define REG_FF3_CSR_ADDR(inst)           ((inst) + 0x00000068)
#define BF_FIFO3_USED_INFO(inst)         ((inst) + 0x00000068), 0x00001000
#define BF_FIFO3_FLUSH_INFO(inst)        ((inst) + 0x00000068), 0x00000110
#define BF_FIFO3_EN_INFO(inst)           ((inst) + 0x00000068), 0x00000111
#define BF_FIFO3_DLINE_EN_INFO(inst)     ((inst) + 0x00000068), 0x00000112

#define REG_FF3_PTR_ADDR(inst)           ((inst) + 0x0000006C)
#define BF_FIFO3_WR_PTR_INFO(inst)       ((inst) + 0x0000006C), 0x00001000
#define BF_FIFO3_RD_PTR_INFO(inst)       ((inst) + 0x0000006C), 0x00001010

#define REG_FF3_INT_ADDR(inst)           ((inst) + 0x00000070)
#define BF_FIFO3_EMPTY_STATUS_INFO(inst) ((inst) + 0x00000070), 0x00000100
#define BF_FIFO3_FULL_STATUS_INFO(inst)  ((inst) + 0x00000070), 0x00000101
#define BF_FIFO3_ALME_STATUS_INFO(inst)  ((inst) + 0x00000070), 0x00000102
#define BF_FIFO3_ALMF_STATUS_INFO(inst)  ((inst) + 0x00000070), 0x00000103
#define BF_FIFO3_UD_STATUS_INFO(inst)    ((inst) + 0x00000070), 0x00000104
#define BF_FIFO3_OV_STATUS_INFO(inst)    ((inst) + 0x00000070), 0x00000105
#define BF_FIFO3_EMPTY_EN_INFO(inst)     ((inst) + 0x00000070), 0x00000108
#define BF_FIFO3_FULL_EN_INFO(inst)      ((inst) + 0x00000070), 0x00000109
#define BF_FIFO3_ALME_EN_INFO(inst)      ((inst) + 0x00000070), 0x0000010A
#define BF_FIFO3_ALMF_EN_INFO(inst)      ((inst) + 0x00000070), 0x0000010B
#define BF_FIFO3_UD_EN_INFO(inst)        ((inst) + 0x00000070), 0x0000010C
#define BF_FIFO3_OV_EN_INFO(inst)        ((inst) + 0x00000070), 0x0000010D
#define BF_FIFO3_EMPTY_CLR_INFO(inst)    ((inst) + 0x00000070), 0x00000110
#define BF_FIFO3_FULL_CLR_INFO(inst)     ((inst) + 0x00000070), 0x00000111
#define BF_FIFO3_ALME_CLR_INFO(inst)     ((inst) + 0x00000070), 0x00000112
#define BF_FIFO3_ALMF_CLR_INFO(inst)     ((inst) + 0x00000070), 0x00000113
#define BF_FIFO3_UD_CLR_INFO(inst)       ((inst) + 0x00000070), 0x00000114
#define BF_FIFO3_OV_CLR_INFO(inst)       ((inst) + 0x00000070), 0x00000115

#define REG_FF3_TH_ADDR(inst)            ((inst) + 0x00000074)
#define BF_FIFO3_ALMF_LEN_INFO(inst)     ((inst) + 0x00000074), 0x00000800
#define BF_FIFO3_ALME_LEN_INFO(inst)     ((inst) + 0x00000074), 0x00000808
#define BF_FIFO3_DLINE_LEN_INFO(inst)    ((inst) + 0x00000074), 0x00001010

#endif /* __ADI_LARK_BF_FIFO_SRAM_H__ */
/*! @} */
