/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.1 at 7/5/2021 7:01:28 AM.
 * 
 * @copyright copyright(c) 2018 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup LARK_BF
 * @{
 */
#ifndef __ADI_LARK_BF_LARK_YODA_H__
#define __ADI_LARK_BF_LARK_YODA_H__

/*============= D E F I N E S ==============*/
#define REG_VENDOR_ID_ADDR                       0x4000C000
#define BF_VENDOR_INFO                           0x4000C000, 0x00000800

#define REG_DEVICE_ID1_ADDR                      0x4000C001
#define BF_DEVICE1_INFO                          0x4000C001, 0x00000800

#define REG_DEVICE_ID2_ADDR                      0x4000C002
#define BF_DEVICE2_INFO                          0x4000C002, 0x00000800

#define REG_REVISION_ADDR                        0x4000C003
#define BF_REV_INFO                              0x4000C003, 0x00000800

#define REG_ADC_DAC_HP_PWR_ADDR                  0x4000C004
#define BF_ADC0_EN_INFO                          0x4000C004, 0x00000100
#define BF_ADC1_EN_INFO                          0x4000C004, 0x00000101
#define BF_ADC2_EN_INFO                          0x4000C004, 0x00000102
#define BF_PB0_EN_INFO                           0x4000C004, 0x00000104

#define REG_PLL_PGA_PWR_ADDR                     0x4000C005
#define BF_PLL_EN_INFO                           0x4000C005, 0x00000100
#define BF_XTAL_EN_INFO                          0x4000C005, 0x00000101
#define BF_PGA0_EN_INFO                          0x4000C005, 0x00000104
#define BF_PGA1_EN_INFO                          0x4000C005, 0x00000105
#define BF_PGA2_EN_INFO                          0x4000C005, 0x00000106

#define REG_DMIC_PWR_ADDR                        0x4000C006
#define BF_DMIC0_EN_INFO                         0x4000C006, 0x00000100
#define BF_DMIC1_EN_INFO                         0x4000C006, 0x00000101
#define BF_DMIC2_EN_INFO                         0x4000C006, 0x00000102
#define BF_DMIC3_EN_INFO                         0x4000C006, 0x00000103
#define BF_DMIC4_EN_INFO                         0x4000C006, 0x00000104
#define BF_DMIC5_EN_INFO                         0x4000C006, 0x00000105
#define BF_DMIC6_EN_INFO                         0x4000C006, 0x00000106
#define BF_DMIC7_EN_INFO                         0x4000C006, 0x00000107

#define REG_SAI_CLK_PWR_ADDR                     0x4000C007
#define BF_SPT0_IN_EN_INFO                       0x4000C007, 0x00000100
#define BF_SPT0_OUT_EN_INFO                      0x4000C007, 0x00000101
#define BF_SPT1_IN_EN_INFO                       0x4000C007, 0x00000102
#define BF_SPT1_OUT_EN_INFO                      0x4000C007, 0x00000103
#define BF_DMIC_CLK_EN_INFO                      0x4000C007, 0x00000104
#define BF_DMIC_CLK1_EN_INFO                     0x4000C007, 0x00000105
#define BF_PDM0_EN_INFO                          0x4000C007, 0x00000106
#define BF_PDM1_EN_INFO                          0x4000C007, 0x00000107

#define REG_DSP_PWR_ADDR                         0x4000C008
#define BF_FDSP_EN_INFO                          0x4000C008, 0x00000100

#define REG_ASRC_PWR_ADDR                        0x4000C009
#define BF_ASRCI0_EN_INFO                        0x4000C009, 0x00000100
#define BF_ASRCI1_EN_INFO                        0x4000C009, 0x00000101
#define BF_ASRCI2_EN_INFO                        0x4000C009, 0x00000102
#define BF_ASRCI3_EN_INFO                        0x4000C009, 0x00000103
#define BF_ASRCO0_EN_INFO                        0x4000C009, 0x00000104
#define BF_ASRCO1_EN_INFO                        0x4000C009, 0x00000105
#define BF_ASRCO2_EN_INFO                        0x4000C009, 0x00000106
#define BF_ASRCO3_EN_INFO                        0x4000C009, 0x00000107

#define REG_FINT_PWR_ADDR                        0x4000C00A
#define BF_FINT0_EN_INFO                         0x4000C00A, 0x00000100
#define BF_FINT1_EN_INFO                         0x4000C00A, 0x00000101
#define BF_FINT2_EN_INFO                         0x4000C00A, 0x00000102
#define BF_FINT3_EN_INFO                         0x4000C00A, 0x00000103
#define BF_FINT4_EN_INFO                         0x4000C00A, 0x00000104
#define BF_FINT5_EN_INFO                         0x4000C00A, 0x00000105
#define BF_FINT6_EN_INFO                         0x4000C00A, 0x00000106
#define BF_FINT7_EN_INFO                         0x4000C00A, 0x00000107

#define REG_FDEC_PWR_ADDR                        0x4000C00B
#define BF_FDEC0_EN_INFO                         0x4000C00B, 0x00000100
#define BF_FDEC1_EN_INFO                         0x4000C00B, 0x00000101
#define BF_FDEC2_EN_INFO                         0x4000C00B, 0x00000102
#define BF_FDEC3_EN_INFO                         0x4000C00B, 0x00000103
#define BF_FDEC4_EN_INFO                         0x4000C00B, 0x00000104
#define BF_FDEC5_EN_INFO                         0x4000C00B, 0x00000105
#define BF_FDEC6_EN_INFO                         0x4000C00B, 0x00000106
#define BF_FDEC7_EN_INFO                         0x4000C00B, 0x00000107

#define REG_KEEP_CM_ADDR                         0x4000C00C
#define BF_CM_KEEP_ALIVE_INFO                    0x4000C00C, 0x00000100

#define REG_MEM_RETAIN_ADDR                      0x4000C00D
#define BF_ADP_MEM_RETAIN_INFO                   0x4000C00D, 0x00000200
#define BF_SOC_MEM_RETAIN_INFO                   0x4000C00D, 0x00000602

#define REG_CHIP_PWR_ADDR                        0x4000C00E
#define BF_PWR_MODE_INFO                         0x4000C00E, 0x00000200
#define BF_MASTER_BLOCK_EN_INFO                  0x4000C00E, 0x00000102
#define BF_CM_STARTUP_OVER_INFO                  0x4000C00E, 0x00000104

#define REG_CLK_CTRL1_ADDR                       0x4000C010
#define BF_PLL_SOURCE_INFO                       0x4000C010, 0x00000300
#define BF_XTAL_MODE_INFO                        0x4000C010, 0x00000103
#define BF_PLL_TYPE_INFO                         0x4000C010, 0x00000104
#define BF_SYNC_SOURCE_INFO                      0x4000C010, 0x00000206

#define REG_CLK_CTRL2_ADDR                       0x4000C011
#define BF_PLL_INPUT_PRESCALER_INFO              0x4000C011, 0x00000300

#define REG_CLK_CTRL3_ADDR                       0x4000C012
#define BF_PLL_INTEGER_DIVIDER_INFO              0x4000C012, 0x00000D00

#define REG_CLK_CTRL4_ADDR                       0x4000C013

#define REG_CLK_CTRL5_ADDR                       0x4000C014
#define BF_PLL_NUMERATOR_INFO                    0x4000C014, 0x00001000

#define REG_CLK_CTRL6_ADDR                       0x4000C015

#define REG_CLK_CTRL7_ADDR                       0x4000C016
#define BF_PLL_DENOMINATOR_INFO                  0x4000C016, 0x00001000

#define REG_CLK_CTRL8_ADDR                       0x4000C017

#define REG_CLK_CTRL9_ADDR                       0x4000C018
#define BF_PLL_UPDATE_INFO                       0x4000C018, 0x00000100

#define REG_CLK_CTRL10_ADDR                      0x4000C019
#define BF_TDSP_CLK_RATE_INFO                    0x4000C019, 0x00000300
#define BF_BUS_CLK_RATE_INFO                     0x4000C019, 0x00000303
#define BF_FFSRAM_RATE_INFO                      0x4000C019, 0x00000206

#define REG_CLK_CTRL11_ADDR                      0x4000C01A
#define BF_UART_CTRL_CLK_RATE_INFO               0x4000C01A, 0x00000304

#define REG_CLK_CTRL12_ADDR                      0x4000C01B
#define BF_FREQ_MULT_EN_INFO                     0x4000C01B, 0x00000100

#define REG_CLK_CTRL13_ADDR                      0x4000C01C
#define BF_MCLK_FREQ_INDEX_INFO                  0x4000C01C, 0x00000200
#define BF_ADC_FREQ_INFO                         0x4000C01C, 0x00000104
#define BF_PLL_FM_BYPASS_INFO                    0x4000C01C, 0x00000107

#define REG_CLK_CTRL14_ADDR                      0x4000C01D
#define BF_ADP_CLOCK_EN_INFO                     0x4000C01D, 0x00001000

#define REG_CLK_CTRL15_ADDR                      0x4000C01E

#define REG_ADC_CTRL1_ADDR                       0x4000C020
#define BF_ADC01_FS_INFO                         0x4000C020, 0x00000300
#define BF_ADC01_DEC_ORDER_INFO                  0x4000C020, 0x00000103
#define BF_ADC2_FS_INFO                          0x4000C020, 0x00000304
#define BF_ADC2_DEC_ORDER_INFO                   0x4000C020, 0x00000107

#define REG_ADC_CTRL2_ADDR                       0x4000C021
#define BF_ADC0_IBIAS_INFO                       0x4000C021, 0x00000300
#define BF_ADC1_IBIAS_INFO                       0x4000C021, 0x00000304

#define REG_ADC_CTRL3_ADDR                       0x4000C022
#define BF_ADC2_IBIAS_INFO                       0x4000C022, 0x00000300

#define REG_ADC_CTRL4_ADDR                       0x4000C023
#define BF_ADC0_HPF_EN_INFO                      0x4000C023, 0x00000200
#define BF_ADC1_HPF_EN_INFO                      0x4000C023, 0x00000202
#define BF_ADC2_HPF_EN_INFO                      0x4000C023, 0x00000204

#define REG_ADC_CTRL5_ADDR                       0x4000C024
#define BF_ADC01_FCOMP_INFO                      0x4000C024, 0x00000100
#define BF_ADC2_FCOMP_INFO                       0x4000C024, 0x00000101
#define BF_ADC_HARD_VOL_INFO                     0x4000C024, 0x00000104
#define BF_ADC_VOL_LINK_INFO                     0x4000C024, 0x00000105
#define BF_ADC_VOL_ZC_INFO                       0x4000C024, 0x00000106

#define REG_ADC_CTRL6_ADDR                       0x4000C025
#define BF_ADC_AIN_CHRG_TIME_INFO                0x4000C025, 0x00000400
#define BF_ADC_CHOP_EN_INFO                      0x4000C025, 0x00000107

#define REG_ADC_CTRL7_ADDR                       0x4000C026
#define BF_ADC_VOC_WKUP_INFO                     0x4000C026, 0x00000100
#define BF_AIN0_INPUT_MODE_INFO                  0x4000C026, 0x00000104
#define BF_AIN1_INPUT_MODE_INFO                  0x4000C026, 0x00000105
#define BF_AIN2_INPUT_MODE_INFO                  0x4000C026, 0x00000106

#define REG_ADC_MUTES_ADDR                       0x4000C027
#define BF_ADC0_MUTE_INFO                        0x4000C027, 0x00000100
#define BF_ADC1_MUTE_INFO                        0x4000C027, 0x00000101
#define BF_ADC2_MUTE_INFO                        0x4000C027, 0x00000102

#define REG_ADC0_VOL_ADDR                        0x4000C028
#define BF_ADC0_VOL_INFO                         0x4000C028, 0x00000800

#define REG_ADC1_VOL_ADDR                        0x4000C029
#define BF_ADC1_VOL_INFO                         0x4000C029, 0x00000800

#define REG_ADC2_VOL_ADDR                        0x4000C02A
#define BF_ADC2_VOL_INFO                         0x4000C02A, 0x00000800

#define REG_ADC_DITHER_LEV_ADDR                  0x4000C02B
#define BF_ADC_DITHER_LEV_INFO                   0x4000C02B, 0x00000300

#define REG_PGA0_CTRL1_ADDR                      0x4000C030
#define BF_PGA0_GAIN_INFO                        0x4000C030, 0x00000B00
#define BF_PGA0_SLEW_DIS_INFO                    0x4000C030, 0x00000107

#define REG_PGA0_CTRL2_ADDR                      0x4000C031

#define REG_PGA1_CTRL1_ADDR                      0x4000C032
#define BF_PGA1_GAIN_INFO                        0x4000C032, 0x00000B00
#define BF_PGA1_SLEW_DIS_INFO                    0x4000C032, 0x00000107

#define REG_PGA1_CTRL2_ADDR                      0x4000C033

#define REG_PGA2_CTRL1_ADDR                      0x4000C034
#define BF_PGA2_GAIN_INFO                        0x4000C034, 0x00000B00
#define BF_PGA2_SLEW_DIS_INFO                    0x4000C034, 0x00000107

#define REG_PGA2_CTRL2_ADDR                      0x4000C035

#define REG_PGA_CTRL1_ADDR                       0x4000C036
#define BF_PGA_SLEW_RATE_INFO                    0x4000C036, 0x00000200
#define BF_PGA_GAIN_LINK_INFO                    0x4000C036, 0x00000104

#define REG_PGA_CTRL2_ADDR                       0x4000C037
#define BF_PGA0_RIN_INFO                         0x4000C037, 0x00000100
#define BF_PGA1_RIN_INFO                         0x4000C037, 0x00000101
#define BF_PGA2_RIN_INFO                         0x4000C037, 0x00000102
#define BF_PGA0_POWER_MODE_INFO                  0x4000C037, 0x00000104
#define BF_PGA1_POWER_MODE_INFO                  0x4000C037, 0x00000105
#define BF_PGA2_POWER_MODE_INFO                  0x4000C037, 0x00000106

#define REG_DMIC_CTRL1_ADDR                      0x4000C040
#define BF_DMIC_CLK_RATE_INFO                    0x4000C040, 0x00000300
#define BF_DMIC_CLK1_RATE_INFO                   0x4000C040, 0x00000304

#define REG_DMIC_CTRL2_ADDR                      0x4000C041
#define BF_DMIC01_FS_INFO                        0x4000C041, 0x00000300
#define BF_DMIC01_DEC_ORDER_INFO                 0x4000C041, 0x00000103
#define BF_DMIC01_HPF_EN_INFO                    0x4000C041, 0x00000204
#define BF_DMIC01_FCOMP_INFO                     0x4000C041, 0x00000106
#define BF_DMIC01_DAT_WIRE_INFO                  0x4000C041, 0x00000107

#define REG_DMIC_CTRL3_ADDR                      0x4000C042
#define BF_DMIC23_FS_INFO                        0x4000C042, 0x00000300
#define BF_DMIC23_DEC_ORDER_INFO                 0x4000C042, 0x00000103
#define BF_DMIC23_HPF_EN_INFO                    0x4000C042, 0x00000204
#define BF_DMIC23_FCOMP_INFO                     0x4000C042, 0x00000106
#define BF_DMIC23_DAT_WIRE_INFO                  0x4000C042, 0x00000107

#define REG_DMIC_CTRL4_ADDR                      0x4000C043
#define BF_DMIC_HARD_VOL_INFO                    0x4000C043, 0x00000100
#define BF_DMIC_VOL_LINK_INFO                    0x4000C043, 0x00000101
#define BF_DMIC_VOL_ZC_INFO                      0x4000C043, 0x00000102

#define REG_DMIC_MUTES_ADDR                      0x4000C044
#define BF_DMIC0_MUTE_INFO                       0x4000C044, 0x00000100
#define BF_DMIC1_MUTE_INFO                       0x4000C044, 0x00000101
#define BF_DMIC2_MUTE_INFO                       0x4000C044, 0x00000102
#define BF_DMIC3_MUTE_INFO                       0x4000C044, 0x00000103
#define BF_DMIC4_MUTE_INFO                       0x4000C044, 0x00000104
#define BF_DMIC5_MUTE_INFO                       0x4000C044, 0x00000105
#define BF_DMIC6_MUTE_INFO                       0x4000C044, 0x00000106
#define BF_DMIC7_MUTE_INFO                       0x4000C044, 0x00000107

#define REG_DMIC_VOL0_ADDR                       0x4000C045
#define BF_DMIC0_VOL_INFO                        0x4000C045, 0x00000800

#define REG_DMIC_VOL1_ADDR                       0x4000C046
#define BF_DMIC1_VOL_INFO                        0x4000C046, 0x00000800

#define REG_DMIC_VOL2_ADDR                       0x4000C047
#define BF_DMIC2_VOL_INFO                        0x4000C047, 0x00000800

#define REG_DMIC_VOL3_ADDR                       0x4000C048
#define BF_DMIC3_VOL_INFO                        0x4000C048, 0x00000800

#define REG_DMIC_CTRL5_ADDR                      0x4000C049
#define BF_DMIC45_FS_INFO                        0x4000C049, 0x00000300
#define BF_DMIC45_HPF_EN_INFO                    0x4000C049, 0x00000203
#define BF_DMIC45_DEC_ORDER_INFO                 0x4000C049, 0x00000105
#define BF_DMIC45_FCOMP_INFO                     0x4000C049, 0x00000106
#define BF_DMIC45_EDGE_INFO                      0x4000C049, 0x00000107

#define REG_DMIC_CTRL6_ADDR                      0x4000C04A
#define BF_DMIC67_FS_INFO                        0x4000C04A, 0x00000300
#define BF_DMIC67_HPF_EN_INFO                    0x4000C04A, 0x00000203
#define BF_DMIC67_DEC_ORDER_INFO                 0x4000C04A, 0x00000105
#define BF_DMIC67_FCOMP_INFO                     0x4000C04A, 0x00000106
#define BF_DMIC67_EDGE_INFO                      0x4000C04A, 0x00000107

#define REG_DMIC_CTRL7_ADDR                      0x4000C04B
#define BF_DMIC01_MAP_INFO                       0x4000C04B, 0x00000100
#define BF_DMIC23_MAP_INFO                       0x4000C04B, 0x00000101
#define BF_DMIC45_MAP_INFO                       0x4000C04B, 0x00000102
#define BF_DMIC67_MAP_INFO                       0x4000C04B, 0x00000103
#define BF_DMIC_CLK1_PIN_SRC_INFO                0x4000C04B, 0x00000204

#define REG_DMIC_VOL4_ADDR                       0x4000C04C
#define BF_DMIC4_VOL_INFO                        0x4000C04C, 0x00000800

#define REG_DMIC_VOL5_ADDR                       0x4000C04D
#define BF_DMIC5_VOL_INFO                        0x4000C04D, 0x00000800

#define REG_DMIC_VOL6_ADDR                       0x4000C04E
#define BF_DMIC6_VOL_INFO                        0x4000C04E, 0x00000800

#define REG_DMIC_VOL7_ADDR                       0x4000C04F
#define BF_DMIC7_VOL_INFO                        0x4000C04F, 0x00000800

#define REG_DAC_CTRL1_ADDR                       0x4000C050
#define BF_DAC_FS_INFO                           0x4000C050, 0x00000300
#define BF_DAC_FCOMP_INFO                        0x4000C050, 0x00000103
#define BF_DAC_LPM_INFO                          0x4000C050, 0x00000106
#define BF_DAC_MORE_FILT_INFO                    0x4000C050, 0x00000107

#define REG_DAC_CTRL2_ADDR                       0x4000C051
#define BF_DAC_HARD_VOL_INFO                     0x4000C051, 0x00000101
#define BF_DAC_VOL_ZC_INFO                       0x4000C051, 0x00000102
#define BF_DAC_LPM_II_INFO                       0x4000C051, 0x00000103
#define BF_DAC0_HPF_EN_INFO                      0x4000C051, 0x00000104
#define BF_DAC0_MUTE_INFO                        0x4000C051, 0x00000106
#define BF_DAC0_FORCE_MUTE_INFO                  0x4000C051, 0x00000107

#define REG_DAC_VOL0_ADDR                        0x4000C052
#define BF_DAC0_VOL_INFO                         0x4000C052, 0x00000800

#define REG_DAC_ROUTE0_ADDR                      0x4000C053
#define BF_DAC0_ROUTE_INFO                       0x4000C053, 0x00000700

#define REG_HP_CTRL_ADDR                         0x4000C060
#define BF_HP0_MODE_INFO                         0x4000C060, 0x00000100

#define REG_HP_LVMODE_CTRL1_ADDR                 0x4000C061
#define BF_HP_LVMODE_EN_INFO                     0x4000C061, 0x00000100
#define BF_HP_LVMODE_CM_EN_INFO                  0x4000C061, 0x00000101

#define REG_HP_LVMODE_CTRL2_ADDR                 0x4000C062
#define BF_HP_LVMODE_AUTOSW_MODE_INFO            0x4000C062, 0x00000100
#define BF_HP_LVMODE_AUTO_DLY_INFO               0x4000C062, 0x00000301
#define BF_HP_LVMODE_CM_DLY_INFO                 0x4000C062, 0x00000204

#define REG_HP_LVMODE_CTRL3_ADDR                 0x4000C063
#define BF_HP_LVMODE_SWITCH_INFO                 0x4000C063, 0x00000100

#define REG_HPLDO_CTRL_ADDR                      0x4000C066
#define BF_HPLDO_EN_INFO                         0x4000C066, 0x00000100
#define BF_HPLDO_BYPASS_INFO                     0x4000C066, 0x00000101
#define BF_HPLDO_VOUT_SET_INFO                   0x4000C066, 0x00000202

#define REG_PB_CTRL_ADDR                         0x4000C06C
#define BF_PB_POWER_CTRL_INFO                    0x4000C06C, 0x00000200

#define REG_PMU_CTRL1_ADDR                       0x4000C070
#define BF_MEM_VOLT_MODE_INFO                    0x4000C070, 0x00000200

#define REG_PMU_CTRL2_ADDR                       0x4000C071
#define BF_STARTUP_DLYCNT_BYP_INFO               0x4000C071, 0x00000100
#define BF_TDSP_WAIT_MODE_BYP_INFO               0x4000C071, 0x00000104

#define REG_PMU_CTRL3_ADDR                       0x4000C072
#define BF_IRQ_WKUP_EN_INFO                      0x4000C072, 0x00000700

#define REG_PMU_CTRL4_ADDR                       0x4000C073
#define BF_WAKEUP_DLY_INFO                       0x4000C073, 0x00000700
#define BF_DLY_UNIT_SEL_INFO                     0x4000C073, 0x00000107

#define REG_PMU_CTRL5_ADDR                       0x4000C074
#define BF_DLDO_CTRL_INFO                        0x4000C074, 0x00000300

#define REG_FDEC_CTRL1_ADDR                      0x4000C080
#define BF_FDEC01_IN_FS_INFO                     0x4000C080, 0x00000300
#define BF_FDEC01_OUT_FS_INFO                    0x4000C080, 0x00000404

#define REG_FDEC_CTRL2_ADDR                      0x4000C081
#define BF_FDEC23_IN_FS_INFO                     0x4000C081, 0x00000300
#define BF_FDEC23_OUT_FS_INFO                    0x4000C081, 0x00000404

#define REG_FDEC_CTRL3_ADDR                      0x4000C082
#define BF_FDEC45_IN_FS_INFO                     0x4000C082, 0x00000300
#define BF_FDEC45_OUT_FS_INFO                    0x4000C082, 0x00000404

#define REG_FDEC_CTRL4_ADDR                      0x4000C083
#define BF_FDEC67_IN_FS_INFO                     0x4000C083, 0x00000300
#define BF_FDEC67_OUT_FS_INFO                    0x4000C083, 0x00000404

#define REG_FDEC_ROUTE0_ADDR                     0x4000C084
#define BF_FDEC0_ROUTE_INFO                      0x4000C084, 0x00000600

#define REG_FDEC_ROUTE1_ADDR                     0x4000C085
#define BF_FDEC1_ROUTE_INFO                      0x4000C085, 0x00000600

#define REG_FDEC_ROUTE2_ADDR                     0x4000C086
#define BF_FDEC2_ROUTE_INFO                      0x4000C086, 0x00000600

#define REG_FDEC_ROUTE3_ADDR                     0x4000C087
#define BF_FDEC3_ROUTE_INFO                      0x4000C087, 0x00000600

#define REG_FDEC_ROUTE4_ADDR                     0x4000C088
#define BF_FDEC4_ROUTE_INFO                      0x4000C088, 0x00000600

#define REG_FDEC_ROUTE5_ADDR                     0x4000C089
#define BF_FDEC5_ROUTE_INFO                      0x4000C089, 0x00000600

#define REG_FDEC_ROUTE6_ADDR                     0x4000C08A
#define BF_FDEC6_ROUTE_INFO                      0x4000C08A, 0x00000600

#define REG_FDEC_ROUTE7_ADDR                     0x4000C08B
#define BF_FDEC7_ROUTE_INFO                      0x4000C08B, 0x00000600

#define REG_FINT_CTRL1_ADDR                      0x4000C090
#define BF_FINT01_IN_FS_INFO                     0x4000C090, 0x00000400
#define BF_FINT01_OUT_FS_INFO                    0x4000C090, 0x00000304

#define REG_FINT_CTRL2_ADDR                      0x4000C091
#define BF_FINT23_IN_FS_INFO                     0x4000C091, 0x00000400
#define BF_FINT23_OUT_FS_INFO                    0x4000C091, 0x00000304

#define REG_FINT_CTRL3_ADDR                      0x4000C092
#define BF_FINT45_IN_FS_INFO                     0x4000C092, 0x00000400
#define BF_FINT45_OUT_FS_INFO                    0x4000C092, 0x00000304

#define REG_FINT_CTRL4_ADDR                      0x4000C093
#define BF_FINT67_IN_FS_INFO                     0x4000C093, 0x00000400
#define BF_FINT67_OUT_FS_INFO                    0x4000C093, 0x00000304

#define REG_FINT_ROUTE0_ADDR                     0x4000C094
#define BF_FINT0_ROUTE_INFO                      0x4000C094, 0x00000700

#define REG_FINT_ROUTE1_ADDR                     0x4000C095
#define BF_FINT1_ROUTE_INFO                      0x4000C095, 0x00000700

#define REG_FINT_ROUTE2_ADDR                     0x4000C096
#define BF_FINT2_ROUTE_INFO                      0x4000C096, 0x00000700

#define REG_FINT_ROUTE3_ADDR                     0x4000C097
#define BF_FINT3_ROUTE_INFO                      0x4000C097, 0x00000700

#define REG_FINT_ROUTE4_ADDR                     0x4000C098
#define BF_FINT4_ROUTE_INFO                      0x4000C098, 0x00000700

#define REG_FINT_ROUTE5_ADDR                     0x4000C099
#define BF_FINT5_ROUTE_INFO                      0x4000C099, 0x00000700

#define REG_FINT_ROUTE6_ADDR                     0x4000C09A
#define BF_FINT6_ROUTE_INFO                      0x4000C09A, 0x00000700

#define REG_FINT_ROUTE7_ADDR                     0x4000C09B
#define BF_FINT7_ROUTE_INFO                      0x4000C09B, 0x00000700

#define REG_ASRCI_CTRL_ADDR                      0x4000C0A0
#define BF_ASRCI_OUT_FS_INFO                     0x4000C0A0, 0x00000300
#define BF_ASRCI_LPM_II_INFO                     0x4000C0A0, 0x00000103
#define BF_ASRCI_SOURCE_INFO                     0x4000C0A0, 0x00000104
#define BF_ASRCI_LPM_INFO                        0x4000C0A0, 0x00000105
#define BF_ASRCI_VFILT_INFO                      0x4000C0A0, 0x00000106
#define BF_ASRCI_MORE_FILT_INFO                  0x4000C0A0, 0x00000107

#define REG_ASRCI_ROUTE01_ADDR                   0x4000C0A1
#define BF_ASRCI0_ROUTE_INFO                     0x4000C0A1, 0x00000400
#define BF_ASRCI1_ROUTE_INFO                     0x4000C0A1, 0x00000404

#define REG_ASRCI_ROUTE23_ADDR                   0x4000C0A2
#define BF_ASRCI2_ROUTE_INFO                     0x4000C0A2, 0x00000400
#define BF_ASRCI3_ROUTE_INFO                     0x4000C0A2, 0x00000404

#define REG_ASRCO_CTRL_ADDR                      0x4000C0A3
#define BF_ASRCO_IN_FS_INFO                      0x4000C0A3, 0x00000300
#define BF_ASRCO_LPM_II_INFO                     0x4000C0A3, 0x00000103
#define BF_ASRCO_SAI_SEL_INFO                    0x4000C0A3, 0x00000104
#define BF_ASRCO_LPM_INFO                        0x4000C0A3, 0x00000105
#define BF_ASRCO_VFILT_INFO                      0x4000C0A3, 0x00000106
#define BF_ASRCO_MORE_FILT_INFO                  0x4000C0A3, 0x00000107

#define REG_ASRCO_ROUTE0_ADDR                    0x4000C0A4
#define BF_ASRCO0_ROUTE_INFO                     0x4000C0A4, 0x00000600

#define REG_ASRCO_ROUTE1_ADDR                    0x4000C0A5
#define BF_ASRCO1_ROUTE_INFO                     0x4000C0A5, 0x00000600

#define REG_ASRCO_ROUTE2_ADDR                    0x4000C0A6
#define BF_ASRCO2_ROUTE_INFO                     0x4000C0A6, 0x00000600

#define REG_ASRCO_ROUTE3_ADDR                    0x4000C0A7
#define BF_ASRCO3_ROUTE_INFO                     0x4000C0A7, 0x00000600

#define REG_FDSP_RUN_ADDR                        0x4000C0B0
#define BF_FDSP_RUN_INFO                         0x4000C0B0, 0x00000100

#define REG_FDSP_CTRL1_ADDR                      0x4000C0B1
#define BF_FDSP_BANK_SEL_INFO                    0x4000C0B1, 0x00000200
#define BF_FDSP_RAMP_MODE_INFO                   0x4000C0B1, 0x00000102
#define BF_FDSP_ZERO_STATE_INFO                  0x4000C0B1, 0x00000103
#define BF_FDSP_RAMP_RATE_INFO                   0x4000C0B1, 0x00000404

#define REG_FDSP_CTRL2_ADDR                      0x4000C0B2
#define BF_FDSP_LAMBDA_INFO                      0x4000C0B2, 0x00000600

#define REG_FDSP_CTRL3_ADDR                      0x4000C0B3
#define BF_FDSP_COPY_AB_INFO                     0x4000C0B3, 0x00000100
#define BF_FDSP_COPY_AC_INFO                     0x4000C0B3, 0x00000101
#define BF_FDSP_COPY_BA_INFO                     0x4000C0B3, 0x00000102
#define BF_FDSP_COPY_BC_INFO                     0x4000C0B3, 0x00000103
#define BF_FDSP_COPY_CA_INFO                     0x4000C0B3, 0x00000104
#define BF_FDSP_COPY_CB_INFO                     0x4000C0B3, 0x00000105
#define BF_FDSP_COPY_DONE_CLEAR_INFO             0x4000C0B3, 0x00000107

#define REG_FDSP_CTRL4_ADDR                      0x4000C0B4
#define BF_FDSP_RATE_SOURCE_INFO                 0x4000C0B4, 0x00000400
#define BF_FDSP_EXP_ATK_SPEED_INFO               0x4000C0B4, 0x00000104
#define BF_FDSP_ONZ_SOURCE_INFO                  0x4000C0B4, 0x00000105

#define REG_FDSP_CTRL5_ADDR                      0x4000C0B5
#define BF_FDSP_RATE_DIV_INFO                    0x4000C0B5, 0x00001000

#define REG_FDSP_CTRL6_ADDR                      0x4000C0B6

#define REG_FDSP_CTRL7_ADDR                      0x4000C0B7
#define BF_FDSP_MOD_N_INFO                       0x4000C0B7, 0x00000600

#define REG_FDSP_CTRL8_ADDR                      0x4000C0B8
#define BF_FDSP_REG_COND0_INFO                   0x4000C0B8, 0x00000100
#define BF_FDSP_REG_COND1_INFO                   0x4000C0B8, 0x00000101
#define BF_FDSP_REG_COND2_INFO                   0x4000C0B8, 0x00000102
#define BF_FDSP_REG_COND3_INFO                   0x4000C0B8, 0x00000103
#define BF_FDSP_REG_COND4_INFO                   0x4000C0B8, 0x00000104
#define BF_FDSP_REG_COND5_INFO                   0x4000C0B8, 0x00000105
#define BF_FDSP_REG_COND6_INFO                   0x4000C0B8, 0x00000106
#define BF_FDSP_REG_COND7_INFO                   0x4000C0B8, 0x00000107

#define REG_FDSP_SL_ADDR_ADDR                    0x4000C0B9
#define BF_FDSP_SL_ADDR_INFO                     0x4000C0B9, 0x00000700

#define REG_FDSP_SL_P0_0_ADDR                    0x4000C0BA
#define BF_FDSP_SL_P0_INFO                       0x4000C0BA, 0x00002000

#define REG_FDSP_SL_P0_1_ADDR                    0x4000C0BB

#define REG_FDSP_SL_P0_2_ADDR                    0x4000C0BC

#define REG_FDSP_SL_P0_3_ADDR                    0x4000C0BD

#define REG_FDSP_SL_P1_0_ADDR                    0x4000C0BE
#define BF_FDSP_SL_P1_INFO                       0x4000C0BE, 0x00002000

#define REG_FDSP_SL_P1_1_ADDR                    0x4000C0BF

#define REG_FDSP_SL_P1_2_ADDR                    0x4000C0C0

#define REG_FDSP_SL_P1_3_ADDR                    0x4000C0C1

#define REG_FDSP_SL_P2_0_ADDR                    0x4000C0C2
#define BF_FDSP_SL_P2_INFO                       0x4000C0C2, 0x00002000

#define REG_FDSP_SL_P2_1_ADDR                    0x4000C0C3

#define REG_FDSP_SL_P2_2_ADDR                    0x4000C0C4

#define REG_FDSP_SL_P2_3_ADDR                    0x4000C0C5

#define REG_FDSP_SL_P3_0_ADDR                    0x4000C0C6
#define BF_FDSP_SL_P3_INFO                       0x4000C0C6, 0x00002000

#define REG_FDSP_SL_P3_1_ADDR                    0x4000C0C7

#define REG_FDSP_SL_P3_2_ADDR                    0x4000C0C8

#define REG_FDSP_SL_P3_3_ADDR                    0x4000C0C9

#define REG_FDSP_SL_P4_0_ADDR                    0x4000C0CA
#define BF_FDSP_SL_P4_INFO                       0x4000C0CA, 0x00002000

#define REG_FDSP_SL_P4_1_ADDR                    0x4000C0CB

#define REG_FDSP_SL_P4_2_ADDR                    0x4000C0CC

#define REG_FDSP_SL_P4_3_ADDR                    0x4000C0CD

#define REG_FDSP_SL_UPDATE_ADDR                  0x4000C0CE
#define BF_FDSP_SL_UPDATE_INFO                   0x4000C0CE, 0x00000100

#define REG_FDSP_ONZ_MASK0_ADDR                  0x4000C0CF
#define BF_FDSP_ONZ_MASK_INFO                    0x4000C0CF, 0x00001800

#define REG_FDSP_ONZ_MASK1_ADDR                  0x4000C0D0

#define REG_FDSP_ONZ_MASK2_ADDR                  0x4000C0D1

#define REG_EQ_CFG_ADDR                          0x4000C0D2
#define BF_EQ_RUN_INFO                           0x4000C0D2, 0x00000100
#define BF_EQ_BANK_SEL_INFO                      0x4000C0D2, 0x00000101
#define BF_EQ_CLEAR_INFO                         0x4000C0D2, 0x00000104

#define REG_EQ_ROUTE_ADDR                        0x4000C0D3
#define BF_EQ_ROUTE_INFO                         0x4000C0D3, 0x00000700

#define REG_TDSP_SOFT_RESET_ADDR                 0x4000C0D4
#define BF_TDSP_SOFT_RESET_INFO                  0x4000C0D4, 0x00000100

#define REG_TDSP_ALTVEC_EN_ADDR                  0x4000C0D5
#define BF_TDSP_ALTVEC_EN_INFO                   0x4000C0D5, 0x00000100

#define REG_TDSP_ALTVEC_ADDR0_ADDR               0x4000C0D8
#define BF_TDSP_ALTVEC_ADDR_INFO                 0x4000C0D8, 0x00002000

#define REG_TDSP_ALTVEC_ADDR1_ADDR               0x4000C0D9

#define REG_TDSP_ALTVEC_ADDR2_ADDR               0x4000C0DA

#define REG_TDSP_ALTVEC_ADDR3_ADDR               0x4000C0DB

#define REG_TDSP_RUN_ADDR                        0x4000C0DC
#define BF_TDSP_RUN_INFO                         0x4000C0DC, 0x00000100

#define REG_TDSP_GPI_ADDR                        0x4000C0DD
#define BF_TDSP_GPI_INFO                         0x4000C0DD, 0x00000602

#define REG_SPT0_CTRL1_ADDR                      0x4000C0E0
#define BF_SPT0_SAI_MODE_INFO                    0x4000C0E0, 0x00000100
#define BF_SPT0_DATA_FORMAT_INFO                 0x4000C0E0, 0x00000301
#define BF_SPT0_SLOT_WIDTH_INFO                  0x4000C0E0, 0x00000204
#define BF_SPT0_TRI_STATE_INFO                   0x4000C0E0, 0x00000106

#define REG_SPT0_CTRL2_ADDR                      0x4000C0E1
#define BF_SPT0_BCLK_SRC_INFO                    0x4000C0E1, 0x00000300
#define BF_SPT0_BCLK_POL_INFO                    0x4000C0E1, 0x00000103

#define REG_SPT0_CTRL3_ADDR                      0x4000C0E2
#define BF_SPT0_LRCLK_SRC_INFO                   0x4000C0E2, 0x00000400
#define BF_SPT0_LRCLK_POL_INFO                   0x4000C0E2, 0x00000104

#define REG_SPT0_ROUTE0_ADDR                     0x4000C0E3
#define BF_SPT0_OUT_ROUTE0_INFO                  0x4000C0E3, 0x00000600

#define REG_SPT0_ROUTE1_ADDR                     0x4000C0E4
#define BF_SPT0_OUT_ROUTE1_INFO                  0x4000C0E4, 0x00000600

#define REG_SPT0_ROUTE2_ADDR                     0x4000C0E5
#define BF_SPT0_OUT_ROUTE2_INFO                  0x4000C0E5, 0x00000600

#define REG_SPT0_ROUTE3_ADDR                     0x4000C0E6
#define BF_SPT0_OUT_ROUTE3_INFO                  0x4000C0E6, 0x00000600

#define REG_SPT0_ROUTE4_ADDR                     0x4000C0E7
#define BF_SPT0_OUT_ROUTE4_INFO                  0x4000C0E7, 0x00000600

#define REG_SPT0_ROUTE5_ADDR                     0x4000C0E8
#define BF_SPT0_OUT_ROUTE5_INFO                  0x4000C0E8, 0x00000600

#define REG_SPT0_ROUTE6_ADDR                     0x4000C0E9
#define BF_SPT0_OUT_ROUTE6_INFO                  0x4000C0E9, 0x00000600

#define REG_SPT0_ROUTE7_ADDR                     0x4000C0EA
#define BF_SPT0_OUT_ROUTE7_INFO                  0x4000C0EA, 0x00000600

#define REG_SPT0_ROUTE8_ADDR                     0x4000C0EB
#define BF_SPT0_OUT_ROUTE8_INFO                  0x4000C0EB, 0x00000600

#define REG_SPT0_ROUTE9_ADDR                     0x4000C0EC
#define BF_SPT0_OUT_ROUTE9_INFO                  0x4000C0EC, 0x00000600

#define REG_SPT0_ROUTE10_ADDR                    0x4000C0ED
#define BF_SPT0_OUT_ROUTE10_INFO                 0x4000C0ED, 0x00000600

#define REG_SPT0_ROUTE11_ADDR                    0x4000C0EE
#define BF_SPT0_OUT_ROUTE11_INFO                 0x4000C0EE, 0x00000600

#define REG_SPT0_ROUTE12_ADDR                    0x4000C0EF
#define BF_SPT0_OUT_ROUTE12_INFO                 0x4000C0EF, 0x00000600

#define REG_SPT0_ROUTE13_ADDR                    0x4000C0F0
#define BF_SPT0_OUT_ROUTE13_INFO                 0x4000C0F0, 0x00000600

#define REG_SPT0_ROUTE14_ADDR                    0x4000C0F1
#define BF_SPT0_OUT_ROUTE14_INFO                 0x4000C0F1, 0x00000600

#define REG_SPT0_ROUTE15_ADDR                    0x4000C0F2
#define BF_SPT0_OUT_ROUTE15_INFO                 0x4000C0F2, 0x00000600

#define REG_SPT1_CTRL1_ADDR                      0x4000C0F3
#define BF_SPT1_SAI_MODE_INFO                    0x4000C0F3, 0x00000100
#define BF_SPT1_DATA_FORMAT_INFO                 0x4000C0F3, 0x00000301
#define BF_SPT1_SLOT_WIDTH_INFO                  0x4000C0F3, 0x00000204
#define BF_SPT1_TRI_STATE_INFO                   0x4000C0F3, 0x00000106

#define REG_SPT1_CTRL2_ADDR                      0x4000C0F4
#define BF_SPT1_BCLK_SRC_INFO                    0x4000C0F4, 0x00000300
#define BF_SPT1_BCLK_POL_INFO                    0x4000C0F4, 0x00000103

#define REG_SPT1_CTRL3_ADDR                      0x4000C0F5
#define BF_SPT1_LRCLK_SRC_INFO                   0x4000C0F5, 0x00000400
#define BF_SPT1_LRCLK_POL_INFO                   0x4000C0F5, 0x00000104

#define REG_SPT1_ROUTE0_ADDR                     0x4000C0F6
#define BF_SPT1_OUT_ROUTE0_INFO                  0x4000C0F6, 0x00000600

#define REG_SPT1_ROUTE1_ADDR                     0x4000C0F7
#define BF_SPT1_OUT_ROUTE1_INFO                  0x4000C0F7, 0x00000600

#define REG_SPT1_ROUTE2_ADDR                     0x4000C0F8
#define BF_SPT1_OUT_ROUTE2_INFO                  0x4000C0F8, 0x00000600

#define REG_SPT1_ROUTE3_ADDR                     0x4000C0F9
#define BF_SPT1_OUT_ROUTE3_INFO                  0x4000C0F9, 0x00000600

#define REG_SPT1_ROUTE4_ADDR                     0x4000C0FA
#define BF_SPT1_OUT_ROUTE4_INFO                  0x4000C0FA, 0x00000600

#define REG_SPT1_ROUTE5_ADDR                     0x4000C0FB
#define BF_SPT1_OUT_ROUTE5_INFO                  0x4000C0FB, 0x00000600

#define REG_SPT1_ROUTE6_ADDR                     0x4000C0FC
#define BF_SPT1_OUT_ROUTE6_INFO                  0x4000C0FC, 0x00000600

#define REG_SPT1_ROUTE7_ADDR                     0x4000C0FD
#define BF_SPT1_OUT_ROUTE7_INFO                  0x4000C0FD, 0x00000600

#define REG_SPT1_ROUTE8_ADDR                     0x4000C0FE
#define BF_SPT1_OUT_ROUTE8_INFO                  0x4000C0FE, 0x00000600

#define REG_SPT1_ROUTE9_ADDR                     0x4000C0FF
#define BF_SPT1_OUT_ROUTE9_INFO                  0x4000C0FF, 0x00000600

#define REG_SPT1_ROUTE10_ADDR                    0x4000C100
#define BF_SPT1_OUT_ROUTE10_INFO                 0x4000C100, 0x00000600

#define REG_SPT1_ROUTE11_ADDR                    0x4000C101
#define BF_SPT1_OUT_ROUTE11_INFO                 0x4000C101, 0x00000600

#define REG_SPT1_ROUTE12_ADDR                    0x4000C102
#define BF_SPT1_OUT_ROUTE12_INFO                 0x4000C102, 0x00000600

#define REG_SPT1_ROUTE13_ADDR                    0x4000C103
#define BF_SPT1_OUT_ROUTE13_INFO                 0x4000C103, 0x00000600

#define REG_SPT1_ROUTE14_ADDR                    0x4000C104
#define BF_SPT1_OUT_ROUTE14_INFO                 0x4000C104, 0x00000600

#define REG_SPT1_ROUTE15_ADDR                    0x4000C105
#define BF_SPT1_OUT_ROUTE15_INFO                 0x4000C105, 0x00000600

#define REG_PDM_CTRL1_ADDR                       0x4000C118
#define BF_PDM_FS_INFO                           0x4000C118, 0x00000300
#define BF_PDM_FCOMP_INFO                        0x4000C118, 0x00000103
#define BF_PDM_RATE_INFO                         0x4000C118, 0x00000104
#define BF_PDM_MORE_FILT_INFO                    0x4000C118, 0x00000107

#define REG_PDM_CTRL2_ADDR                       0x4000C119
#define BF_PDM_VOL_LINK_INFO                     0x4000C119, 0x00000100
#define BF_PDM_HARD_VOL_INFO                     0x4000C119, 0x00000101
#define BF_PDM_VOL_ZC_INFO                       0x4000C119, 0x00000102
#define BF_PDM0_HPF_EN_INFO                      0x4000C119, 0x00000104
#define BF_PDM1_HPF_EN_INFO                      0x4000C119, 0x00000105
#define BF_PDM0_MUTE_INFO                        0x4000C119, 0x00000106
#define BF_PDM1_MUTE_INFO                        0x4000C119, 0x00000107

#define REG_PDM_VOL0_ADDR                        0x4000C11A
#define BF_PDM0_VOL_INFO                         0x4000C11A, 0x00000800

#define REG_PDM_VOL1_ADDR                        0x4000C11B
#define BF_PDM1_VOL_INFO                         0x4000C11B, 0x00000800

#define REG_PDM_ROUTE0_ADDR                      0x4000C11C
#define BF_PDM0_ROUTE_INFO                       0x4000C11C, 0x00000700

#define REG_PDM_ROUTE1_ADDR                      0x4000C11D
#define BF_PDM1_ROUTE_INFO                       0x4000C11D, 0x00000700

#define REG_MP_CTRL1_ADDR                        0x4000C121
#define BF_MP0_MODE_INFO                         0x4000C121, 0x00000400
#define BF_MP1_MODE_INFO                         0x4000C121, 0x00000404

#define REG_MP_CTRL2_ADDR                        0x4000C122
#define BF_MP2_MODE_INFO                         0x4000C122, 0x00000400
#define BF_MP3_MODE_INFO                         0x4000C122, 0x00000404

#define REG_MP_CTRL3_ADDR                        0x4000C123
#define BF_MP4_MODE_INFO                         0x4000C123, 0x00000400
#define BF_MP5_MODE_INFO                         0x4000C123, 0x00000404

#define REG_MP_CTRL4_ADDR                        0x4000C124
#define BF_MP6_MODE_INFO                         0x4000C124, 0x00000400
#define BF_MP7_MODE_INFO                         0x4000C124, 0x00000404

#define REG_MP_CTRL5_ADDR                        0x4000C125
#define BF_MP8_MODE_INFO                         0x4000C125, 0x00000400
#define BF_MP9_MODE_INFO                         0x4000C125, 0x00000404

#define REG_MP_CTRL6_ADDR                        0x4000C126
#define BF_MP10_MODE_INFO                        0x4000C126, 0x00000400
#define BF_MP11_MODE_INFO                        0x4000C126, 0x00000404

#define REG_MP_CTRL7_ADDR                        0x4000C127
#define BF_MP12_MODE_INFO                        0x4000C127, 0x00000400
#define BF_MP13_MODE_INFO                        0x4000C127, 0x00000404

#define REG_MP_CTRL8_ADDR                        0x4000C128
#define BF_MP14_MODE_INFO                        0x4000C128, 0x00000400
#define BF_MP15_MODE_INFO                        0x4000C128, 0x00000404

#define REG_MP_CTRL9_ADDR                        0x4000C129
#define BF_MP16_MODE_INFO                        0x4000C129, 0x00000400
#define BF_MP17_MODE_INFO                        0x4000C129, 0x00000404

#define REG_MP_CTRL10_ADDR                       0x4000C12A
#define BF_MP18_MODE_INFO                        0x4000C12A, 0x00000400
#define BF_MP19_MODE_INFO                        0x4000C12A, 0x00000404

#define REG_MP_CTRL11_ADDR                       0x4000C12B
#define BF_MP20_MODE_INFO                        0x4000C12B, 0x00000400
#define BF_MP21_MODE_INFO                        0x4000C12B, 0x00000404

#define REG_MP_CTRL12_ADDR                       0x4000C12C
#define BF_MP22_MODE_INFO                        0x4000C12C, 0x00000400
#define BF_MP23_MODE_INFO                        0x4000C12C, 0x00000404

#define REG_MP_CTRL13_ADDR                       0x4000C12D
#define BF_MP24_MODE_INFO                        0x4000C12D, 0x00000400
#define BF_MP25_MODE_INFO                        0x4000C12D, 0x00000404

#define REG_MP_DB_CTRL_ADDR                      0x4000C12E
#define BF_GPI_DB_INFO                           0x4000C12E, 0x00000300
#define BF_IRQ_IN_DB_INFO                        0x4000C12E, 0x00000304

#define REG_MP_MCLKO_RATE_ADDR                   0x4000C12F
#define BF_MCLKO_RATE_INFO                       0x4000C12F, 0x00000300

#define REG_MP_GPIO_CTRL1_ADDR                   0x4000C130
#define BF_GPIO0_OUT_INFO                        0x4000C130, 0x00000100
#define BF_GPIO1_OUT_INFO                        0x4000C130, 0x00000101
#define BF_GPIO2_OUT_INFO                        0x4000C130, 0x00000102
#define BF_GPIO3_OUT_INFO                        0x4000C130, 0x00000103
#define BF_GPIO4_OUT_INFO                        0x4000C130, 0x00000104
#define BF_GPIO5_OUT_INFO                        0x4000C130, 0x00000105
#define BF_GPIO6_OUT_INFO                        0x4000C130, 0x00000106
#define BF_GPIO7_OUT_INFO                        0x4000C130, 0x00000107

#define REG_MP_GPIO_CTRL2_ADDR                   0x4000C131
#define BF_GPIO8_OUT_INFO                        0x4000C131, 0x00000100
#define BF_GPIO9_OUT_INFO                        0x4000C131, 0x00000101
#define BF_GPIO10_OUT_INFO                       0x4000C131, 0x00000102
#define BF_GPIO11_OUT_INFO                       0x4000C131, 0x00000103
#define BF_GPIO12_OUT_INFO                       0x4000C131, 0x00000104
#define BF_GPIO13_OUT_INFO                       0x4000C131, 0x00000105
#define BF_GPIO14_OUT_INFO                       0x4000C131, 0x00000106
#define BF_GPIO15_OUT_INFO                       0x4000C131, 0x00000107

#define REG_MP_GPIO_CTRL3_ADDR                   0x4000C132
#define BF_GPIO16_OUT_INFO                       0x4000C132, 0x00000100
#define BF_GPIO17_OUT_INFO                       0x4000C132, 0x00000101
#define BF_GPIO18_OUT_INFO                       0x4000C132, 0x00000102
#define BF_GPIO19_OUT_INFO                       0x4000C132, 0x00000103
#define BF_GPIO20_OUT_INFO                       0x4000C132, 0x00000104
#define BF_GPIO21_OUT_INFO                       0x4000C132, 0x00000105
#define BF_GPIO22_OUT_INFO                       0x4000C132, 0x00000106
#define BF_GPIO23_OUT_INFO                       0x4000C132, 0x00000107

#define REG_MP_GPIO_CTRL4_ADDR                   0x4000C133
#define BF_GPIO24_OUT_INFO                       0x4000C133, 0x00000100
#define BF_GPIO25_OUT_INFO                       0x4000C133, 0x00000101

#define REG_DMIC_CLK_CTRL_ADDR                   0x4000C134
#define BF_DMIC_CLK_DRIVE_INFO                   0x4000C134, 0x00000200
#define BF_DMIC_CLK_SLEW_INFO                    0x4000C134, 0x00000102
#define BF_DMIC_CLK_PULL_EN_INFO                 0x4000C134, 0x00000104
#define BF_DMIC_CLK_PULL_SEL_INFO                0x4000C134, 0x00000105

#define REG_DMIC01_CTRL_ADDR                     0x4000C135
#define BF_DMIC01_DRIVE_INFO                     0x4000C135, 0x00000200
#define BF_DMIC01_SLEW_INFO                      0x4000C135, 0x00000102
#define BF_DMIC01_PULL_EN_INFO                   0x4000C135, 0x00000104
#define BF_DMIC01_PULL_SEL_INFO                  0x4000C135, 0x00000105

#define REG_DMIC23_CTRL_ADDR                     0x4000C136
#define BF_DMIC23_DRIVE_INFO                     0x4000C136, 0x00000200
#define BF_DMIC23_SLEW_INFO                      0x4000C136, 0x00000102
#define BF_DMIC23_PULL_EN_INFO                   0x4000C136, 0x00000104
#define BF_DMIC23_PULL_SEL_INFO                  0x4000C136, 0x00000105

#define REG_BCLK0_CTRL_ADDR                      0x4000C137
#define BF_BCLK0_DRIVE_INFO                      0x4000C137, 0x00000200
#define BF_BCLK0_SLEW_INFO                       0x4000C137, 0x00000102
#define BF_BCLK0_PULL_EN_INFO                    0x4000C137, 0x00000104
#define BF_BCLK0_PULL_SEL_INFO                   0x4000C137, 0x00000105

#define REG_FSYNC0_CTRL_ADDR                     0x4000C138
#define BF_FSYNC0_DRIVE_INFO                     0x4000C138, 0x00000200
#define BF_FSYNC0_SLEW_INFO                      0x4000C138, 0x00000102
#define BF_FSYNC0_PULL_EN_INFO                   0x4000C138, 0x00000104
#define BF_FSYNC0_PULL_SEL_INFO                  0x4000C138, 0x00000105

#define REG_SDATAO0_CTRL_ADDR                    0x4000C139
#define BF_SDATAO0_DRIVE_INFO                    0x4000C139, 0x00000200
#define BF_SDATAO0_SLEW_INFO                     0x4000C139, 0x00000102
#define BF_SDATAO0_PULL_EN_INFO                  0x4000C139, 0x00000104
#define BF_SDATAO0_PULL_SEL_INFO                 0x4000C139, 0x00000105

#define REG_SDATAI0_CTRL_ADDR                    0x4000C13A
#define BF_SDATAI0_DRIVE_INFO                    0x4000C13A, 0x00000200
#define BF_SDATAI0_SLEW_INFO                     0x4000C13A, 0x00000102
#define BF_SDATAI0_PULL_EN_INFO                  0x4000C13A, 0x00000104
#define BF_SDATAI0_PULL_SEL_INFO                 0x4000C13A, 0x00000105

#define REG_BCLK1_CTRL_ADDR                      0x4000C13B
#define BF_BCLK1_DRIVE_INFO                      0x4000C13B, 0x00000200
#define BF_BCLK1_SLEW_INFO                       0x4000C13B, 0x00000102
#define BF_BCLK1_PULL_EN_INFO                    0x4000C13B, 0x00000104
#define BF_BCLK1_PULL_SEL_INFO                   0x4000C13B, 0x00000105

#define REG_FSYNC1_CTRL_ADDR                     0x4000C13C
#define BF_FSYNC1_DRIVE_INFO                     0x4000C13C, 0x00000200
#define BF_FSYNC1_SLEW_INFO                      0x4000C13C, 0x00000102
#define BF_FSYNC1_PULL_EN_INFO                   0x4000C13C, 0x00000104
#define BF_FSYNC1_PULL_SEL_INFO                  0x4000C13C, 0x00000105

#define REG_SDATAO1_CTRL_ADDR                    0x4000C13D
#define BF_SDATAO1_DRIVE_INFO                    0x4000C13D, 0x00000200
#define BF_SDATAO1_SLEW_INFO                     0x4000C13D, 0x00000102
#define BF_SDATAO1_PULL_EN_INFO                  0x4000C13D, 0x00000104
#define BF_SDATAO1_PULL_SEL_INFO                 0x4000C13D, 0x00000105

#define REG_SDATAI1_CTRL_ADDR                    0x4000C13E
#define BF_SDATAI1_DRIVE_INFO                    0x4000C13E, 0x00000200
#define BF_SDATAI1_SLEW_INFO                     0x4000C13E, 0x00000102
#define BF_SDATAI1_PULL_EN_INFO                  0x4000C13E, 0x00000104
#define BF_SDATAI1_PULL_SEL_INFO                 0x4000C13E, 0x00000105

#define REG_QSPIM_CLK_CTRL_ADDR                  0x4000C13F
#define BF_QSPIM_CLK_DRIVE_INFO                  0x4000C13F, 0x00000200
#define BF_QSPIM_CLK_SLEW_INFO                   0x4000C13F, 0x00000102
#define BF_QSPIM_CLK_PULL_EN_INFO                0x4000C13F, 0x00000104
#define BF_QSPIM_CLK_PULL_SEL_INFO               0x4000C13F, 0x00000105

#define REG_QSPIM_CS_CTRL_ADDR                   0x4000C140
#define BF_QSPIM_CS_DRIVE_INFO                   0x4000C140, 0x00000200
#define BF_QSPIM_CS_SLEW_INFO                    0x4000C140, 0x00000102
#define BF_QSPIM_CS_PULL_EN_INFO                 0x4000C140, 0x00000104
#define BF_QSPIM_CS_PULL_SEL_INFO                0x4000C140, 0x00000105

#define REG_QSPIM_SDIO0_CTRL_ADDR                0x4000C141
#define BF_QSPIM_SDIO0_DRIVE_INFO                0x4000C141, 0x00000200
#define BF_QSPIM_SDIO0_SLEW_INFO                 0x4000C141, 0x00000102
#define BF_QSPIM_SDIO0_PULL_EN_INFO              0x4000C141, 0x00000104
#define BF_QSPIM_SDIO0_PULL_SEL_INFO             0x4000C141, 0x00000105

#define REG_QSPIM_SDIO1_CTRL_ADDR                0x4000C142
#define BF_QSPIM_SDIO1_DRIVE_INFO                0x4000C142, 0x00000200
#define BF_QSPIM_SDIO1_SLEW_INFO                 0x4000C142, 0x00000102
#define BF_QSPIM_SDIO1_PULL_EN_INFO              0x4000C142, 0x00000104
#define BF_QSPIM_SDIO1_PULL_SEL_INFO             0x4000C142, 0x00000105

#define REG_QSPIM_SDIO2_CTRL_ADDR                0x4000C143
#define BF_QSPIM_SDIO2_DRIVE_INFO                0x4000C143, 0x00000200
#define BF_QSPIM_SDIO2_SLEW_INFO                 0x4000C143, 0x00000102
#define BF_QSPIM_SDIO2_PULL_EN_INFO              0x4000C143, 0x00000104
#define BF_QSPIM_SDIO2_PULL_SEL_INFO             0x4000C143, 0x00000105

#define REG_QSPIM_SDIO3_CTRL_ADDR                0x4000C144
#define BF_QSPIM_SDIO3_DRIVE_INFO                0x4000C144, 0x00000200
#define BF_QSPIM_SDIO3_SLEW_INFO                 0x4000C144, 0x00000102
#define BF_QSPIM_SDIO3_PULL_EN_INFO              0x4000C144, 0x00000104
#define BF_QSPIM_SDIO3_PULL_SEL_INFO             0x4000C144, 0x00000105

#define REG_UART_COMM_TX_CTRL_ADDR               0x4000C145
#define BF_UART_COMM_TX_DRIVE_INFO               0x4000C145, 0x00000200
#define BF_UART_COMM_TX_SLEW_INFO                0x4000C145, 0x00000102
#define BF_UART_COMM_TX_PULL_EN_INFO             0x4000C145, 0x00000104
#define BF_UART_COMM_TX_PULL_SEL_INFO            0x4000C145, 0x00000105

#define REG_UART_COMM_RX_CTRL_ADDR               0x4000C146
#define BF_UART_COMM_RX_DRIVE_INFO               0x4000C146, 0x00000200
#define BF_UART_COMM_RX_SLEW_INFO                0x4000C146, 0x00000102
#define BF_UART_COMM_RX_PULL_EN_INFO             0x4000C146, 0x00000104
#define BF_UART_COMM_RX_PULL_SEL_INFO            0x4000C146, 0x00000105

#define REG_SELFBOOT_CTRL_ADDR                   0x4000C147
#define BF_SELFBOOT_DRIVE_INFO                   0x4000C147, 0x00000200
#define BF_SELFBOOT_SLEW_INFO                    0x4000C147, 0x00000102
#define BF_SELFBOOT_PULL_EN_INFO                 0x4000C147, 0x00000104
#define BF_SELFBOOT_PULL_SEL_INFO                0x4000C147, 0x00000105

#define REG_IRQ_CTRL_ADDR                        0x4000C148
#define BF_IRQ_DRIVE_INFO                        0x4000C148, 0x00000200
#define BF_IRQ_SLEW_INFO                         0x4000C148, 0x00000102
#define BF_IRQ_PULL_EN_INFO                      0x4000C148, 0x00000104
#define BF_IRQ_PULL_SEL_INFO                     0x4000C148, 0x00000105

#define REG_ROM_BOOT_MODE_CTRL_ADDR              0x4000C149
#define BF_ROM_BOOT_MODE_DRIVE_INFO              0x4000C149, 0x00000200
#define BF_ROM_BOOT_MODE_SLEW_INFO               0x4000C149, 0x00000102
#define BF_ROM_BOOT_MODE_PULL_EN_INFO            0x4000C149, 0x00000104
#define BF_ROM_BOOT_MODE_PULL_SEL_INFO           0x4000C149, 0x00000105

#define REG_TCK_CTRL_ADDR                        0x4000C14A
#define BF_TCK_DRIVE_INFO                        0x4000C14A, 0x00000200
#define BF_TCK_SLEW_INFO                         0x4000C14A, 0x00000102
#define BF_TCK_PULL_EN_INFO                      0x4000C14A, 0x00000104
#define BF_TCK_PULL_SEL_INFO                     0x4000C14A, 0x00000105

#define REG_TMS_CTRL_ADDR                        0x4000C14B
#define BF_TMS_DRIVE_INFO                        0x4000C14B, 0x00000200
#define BF_TMS_SLEW_INFO                         0x4000C14B, 0x00000102
#define BF_TMS_PULL_EN_INFO                      0x4000C14B, 0x00000104
#define BF_TMS_PULL_SEL_INFO                     0x4000C14B, 0x00000105

#define REG_TDO_CTRL_ADDR                        0x4000C14C
#define BF_TDO_DRIVE_INFO                        0x4000C14C, 0x00000200
#define BF_TDO_SLEW_INFO                         0x4000C14C, 0x00000102
#define BF_TDO_PULL_EN_INFO                      0x4000C14C, 0x00000104
#define BF_TDO_PULL_SEL_INFO                     0x4000C14C, 0x00000105

#define REG_TDI_CTRL_ADDR                        0x4000C14D
#define BF_TDI_DRIVE_INFO                        0x4000C14D, 0x00000200
#define BF_TDI_SLEW_INFO                         0x4000C14D, 0x00000102
#define BF_TDI_PULL_EN_INFO                      0x4000C14D, 0x00000104
#define BF_TDI_PULL_SEL_INFO                     0x4000C14D, 0x00000105

#define REG_I2C_SPI_CTRL_ADDR                    0x4000C14E
#define BF_SDA_MISO_DRIVE_INFO                   0x4000C14E, 0x00000100
#define BF_SCL_SCLK_DRIVE_INFO                   0x4000C14E, 0x00000101

#define REG_IRQ_CTRL1_ADDR                       0x4000C150
#define BF_IRQ1_CLEAR_INFO                       0x4000C150, 0x00000100
#define BF_IRQ2_CLEAR_INFO                       0x4000C150, 0x00000101
#define BF_IRQ3_CLEAR_INFO                       0x4000C150, 0x00000102
#define BF_IRQ4_CLEAR_INFO                       0x4000C150, 0x00000103
#define BF_IRQ1_PINOUT_POL_INFO                  0x4000C150, 0x00000104
#define BF_IRQ2_PINOUT_POL_INFO                  0x4000C150, 0x00000105
#define BF_IRQ3_PINOUT_POL_INFO                  0x4000C150, 0x00000106
#define BF_IRQ4_PINOUT_POL_INFO                  0x4000C150, 0x00000107

#define REG_IRQ1_MASK1_ADDR                      0x4000C151
#define BF_IRQ1_DAC0_CLIP_MASK_INFO              0x4000C151, 0x00000100
#define BF_IRQ1_ADC0_CLIP_MASK_INFO              0x4000C151, 0x00000101
#define BF_IRQ1_ADC1_CLIP_MASK_INFO              0x4000C151, 0x00000102
#define BF_IRQ1_ADC2_CLIP_MASK_INFO              0x4000C151, 0x00000103
#define BF_IRQ1_PLL_LOCKED_MASK_INFO             0x4000C151, 0x00000104
#define BF_IRQ1_PLL_UNLOCKED_MASK_INFO           0x4000C151, 0x00000105
#define BF_IRQ1_AVDD_UVW_MASK_INFO               0x4000C151, 0x00000106

#define REG_IRQ1_MASK2_ADDR                      0x4000C152
#define BF_IRQ1_PRAMP_MASK_INFO                  0x4000C152, 0x00000100
#define BF_IRQ1_FDSP_MASK_ONZ_MASK_INFO          0x4000C152, 0x00000101
#define BF_IRQ1_EQ_CLEAR_DONE_MASK_INFO          0x4000C152, 0x00000102
#define BF_IRQ1_ASRCI_LOCKED_MASK_INFO           0x4000C152, 0x00000104
#define BF_IRQ1_ASRCI_UNLOCKED_MASK_INFO         0x4000C152, 0x00000105
#define BF_IRQ1_ASRCO_LOCKED_MASK_INFO           0x4000C152, 0x00000106
#define BF_IRQ1_ASRCO_UNLOCKED_MASK_INFO         0x4000C152, 0x00000107

#define REG_IRQ1_MASK3_ADDR                      0x4000C153
#define BF_IRQ1_SYNC_LOCKED_MASK_INFO            0x4000C153, 0x00000100
#define BF_IRQ1_SYNC_UNLOCKED_MASK_INFO          0x4000C153, 0x00000101
#define BF_IRQ1_SPT0_UNLOCKED_MASK_INFO          0x4000C153, 0x00000102
#define BF_IRQ1_SPT1_UNLOCKED_MASK_INFO          0x4000C153, 0x00000103
#define BF_IRQ1_POWER_UP_COMPLETE_MASK_INFO      0x4000C153, 0x00000104
#define BF_IRQ1_DLDO_DVS_DONE_MASK_INFO          0x4000C153, 0x00000105

#define REG_IRQ1_MASK4_ADDR                      0x4000C154
#define BF_IRQ1_SW_INT0_MASK_INFO                0x4000C154, 0x00000100
#define BF_IRQ1_SW_INT1_MASK_INFO                0x4000C154, 0x00000101
#define BF_IRQ1_SW_INT2_MASK_INFO                0x4000C154, 0x00000102
#define BF_IRQ1_SW_INT3_MASK_INFO                0x4000C154, 0x00000103
#define BF_IRQ1_DATA_SYNC_IRQ_MASK_INFO          0x4000C154, 0x00000104
#define BF_IRQ1_FFSRAM2_IRQ_MASK_INFO            0x4000C154, 0x00000105

#define REG_IRQ1_MASK5_ADDR                      0x4000C155
#define BF_IRQ1_TDSP_ERR_MASK_INFO               0x4000C155, 0x00000100
#define BF_IRQ1_AHB_ERR_MASK_INFO                0x4000C155, 0x00000101
#define BF_IRQ1_AHB_BUSY_MASK_INFO               0x4000C155, 0x00000102
#define BF_IRQ1_WDT_IRQ_MASK_INFO                0x4000C155, 0x00000103

#define REG_IRQ2_MASK1_ADDR                      0x4000C156
#define BF_IRQ2_DAC0_CLIP_MASK_INFO              0x4000C156, 0x00000100
#define BF_IRQ2_ADC0_CLIP_MASK_INFO              0x4000C156, 0x00000101
#define BF_IRQ2_ADC1_CLIP_MASK_INFO              0x4000C156, 0x00000102
#define BF_IRQ2_ADC2_CLIP_MASK_INFO              0x4000C156, 0x00000103
#define BF_IRQ2_PLL_LOCKED_MASK_INFO             0x4000C156, 0x00000104
#define BF_IRQ2_PLL_UNLOCKED_MASK_INFO           0x4000C156, 0x00000105
#define BF_IRQ2_AVDD_UVW_MASK_INFO               0x4000C156, 0x00000106

#define REG_IRQ2_MASK2_ADDR                      0x4000C157
#define BF_IRQ2_PRAMP_MASK_INFO                  0x4000C157, 0x00000100
#define BF_IRQ2_FDSP_MASK_ONZ_MASK_INFO          0x4000C157, 0x00000101
#define BF_IRQ2_EQ_CLEAR_DONE_MASK_INFO          0x4000C157, 0x00000102
#define BF_IRQ2_ASRCI_LOCKED_MASK_INFO           0x4000C157, 0x00000104
#define BF_IRQ2_ASRCI_UNLOCKED_MASK_INFO         0x4000C157, 0x00000105
#define BF_IRQ2_ASRCO_LOCKED_MASK_INFO           0x4000C157, 0x00000106
#define BF_IRQ2_ASRCO_UNLOCKED_MASK_INFO         0x4000C157, 0x00000107

#define REG_IRQ2_MASK3_ADDR                      0x4000C158
#define BF_IRQ2_SYNC_LOCKED_MASK_INFO            0x4000C158, 0x00000100
#define BF_IRQ2_SYNC_UNLOCKED_MASK_INFO          0x4000C158, 0x00000101
#define BF_IRQ2_SPT0_UNLOCKED_MASK_INFO          0x4000C158, 0x00000102
#define BF_IRQ2_SPT1_UNLOCKED_MASK_INFO          0x4000C158, 0x00000103
#define BF_IRQ2_POWER_UP_COMPLETE_MASK_INFO      0x4000C158, 0x00000104
#define BF_IRQ2_DLDO_DVS_DONE_MASK_INFO          0x4000C158, 0x00000105

#define REG_IRQ2_MASK4_ADDR                      0x4000C159
#define BF_IRQ2_SW_INT0_MASK_INFO                0x4000C159, 0x00000100
#define BF_IRQ2_SW_INT1_MASK_INFO                0x4000C159, 0x00000101
#define BF_IRQ2_SW_INT2_MASK_INFO                0x4000C159, 0x00000102
#define BF_IRQ2_SW_INT3_MASK_INFO                0x4000C159, 0x00000103
#define BF_IRQ2_DATA_SYNC_IRQ_MASK_INFO          0x4000C159, 0x00000104
#define BF_IRQ2_FFSRAM2_IRQ_MASK_INFO            0x4000C159, 0x00000105

#define REG_IRQ2_MASK5_ADDR                      0x4000C15A
#define BF_IRQ2_TDSP_ERR_MASK_INFO               0x4000C15A, 0x00000100
#define BF_IRQ2_AHB_ERR_MASK_INFO                0x4000C15A, 0x00000101
#define BF_IRQ2_AHB_BUSY_MASK_INFO               0x4000C15A, 0x00000102
#define BF_IRQ2_WDT_IRQ_MASK_INFO                0x4000C15A, 0x00000103

#define REG_IRQ3_MASK1_ADDR                      0x4000C15B
#define BF_IRQ3_DAC0_CLIP_MASK_INFO              0x4000C15B, 0x00000100
#define BF_IRQ3_ADC0_CLIP_MASK_INFO              0x4000C15B, 0x00000101
#define BF_IRQ3_ADC1_CLIP_MASK_INFO              0x4000C15B, 0x00000102
#define BF_IRQ3_ADC2_CLIP_MASK_INFO              0x4000C15B, 0x00000103
#define BF_IRQ3_PLL_LOCKED_MASK_INFO             0x4000C15B, 0x00000104
#define BF_IRQ3_PLL_UNLOCKED_MASK_INFO           0x4000C15B, 0x00000105
#define BF_IRQ3_AVDD_UVW_MASK_INFO               0x4000C15B, 0x00000106

#define REG_IRQ3_MASK2_ADDR                      0x4000C15C
#define BF_IRQ3_PRAMP_MASK_INFO                  0x4000C15C, 0x00000100
#define BF_IRQ3_FDSP_MASK_ONZ_MASK_INFO          0x4000C15C, 0x00000101
#define BF_IRQ3_EQ_CLEAR_DONE_MASK_INFO          0x4000C15C, 0x00000102
#define BF_IRQ3_ASRCI_LOCKED_MASK_INFO           0x4000C15C, 0x00000104
#define BF_IRQ3_ASRCI_UNLOCKED_MASK_INFO         0x4000C15C, 0x00000105
#define BF_IRQ3_ASRCO_LOCKED_MASK_INFO           0x4000C15C, 0x00000106
#define BF_IRQ3_ASRCO_UNLOCKED_MASK_INFO         0x4000C15C, 0x00000107

#define REG_IRQ3_MASK3_ADDR                      0x4000C15D
#define BF_IRQ3_SYNC_LOCKED_MASK_INFO            0x4000C15D, 0x00000100
#define BF_IRQ3_SYNC_UNLOCKED_MASK_INFO          0x4000C15D, 0x00000101
#define BF_IRQ3_SPT0_UNLOCKED_MASK_INFO          0x4000C15D, 0x00000102
#define BF_IRQ3_SPT1_UNLOCKED_MASK_INFO          0x4000C15D, 0x00000103
#define BF_IRQ3_POWER_UP_COMPLETE_MASK_INFO      0x4000C15D, 0x00000104
#define BF_IRQ3_DLDO_DVS_DONE_MASK_INFO          0x4000C15D, 0x00000105

#define REG_IRQ3_MASK4_ADDR                      0x4000C15E
#define BF_IRQ3_SW_INT0_MASK_INFO                0x4000C15E, 0x00000100
#define BF_IRQ3_SW_INT1_MASK_INFO                0x4000C15E, 0x00000101
#define BF_IRQ3_SW_INT2_MASK_INFO                0x4000C15E, 0x00000102
#define BF_IRQ3_SW_INT3_MASK_INFO                0x4000C15E, 0x00000103
#define BF_IRQ3_DATA_SYNC_IRQ_MASK_INFO          0x4000C15E, 0x00000104
#define BF_IRQ3_FFSRAM2_IRQ_MASK_INFO            0x4000C15E, 0x00000105

#define REG_IRQ3_MASK5_ADDR                      0x4000C15F
#define BF_IRQ3_TDSP_ERR_MASK_INFO               0x4000C15F, 0x00000100
#define BF_IRQ3_AHB_ERR_MASK_INFO                0x4000C15F, 0x00000101
#define BF_IRQ3_AHB_BUSY_MASK_INFO               0x4000C15F, 0x00000102
#define BF_IRQ3_WDT_IRQ_MASK_INFO                0x4000C15F, 0x00000103

#define REG_IRQ4_MASK1_ADDR                      0x4000C160
#define BF_IRQ4_DAC0_CLIP_MASK_INFO              0x4000C160, 0x00000100
#define BF_IRQ4_ADC0_CLIP_MASK_INFO              0x4000C160, 0x00000101
#define BF_IRQ4_ADC1_CLIP_MASK_INFO              0x4000C160, 0x00000102
#define BF_IRQ4_ADC2_CLIP_MASK_INFO              0x4000C160, 0x00000103
#define BF_IRQ4_PLL_LOCKED_MASK_INFO             0x4000C160, 0x00000104
#define BF_IRQ4_PLL_UNLOCKED_MASK_INFO           0x4000C160, 0x00000105
#define BF_IRQ4_AVDD_UVW_MASK_INFO               0x4000C160, 0x00000106

#define REG_IRQ4_MASK2_ADDR                      0x4000C161
#define BF_IRQ4_PRAMP_MASK_INFO                  0x4000C161, 0x00000100
#define BF_IRQ4_FDSP_MASK_ONZ_MASK_INFO          0x4000C161, 0x00000101
#define BF_IRQ4_EQ_CLEAR_DONE_MASK_INFO          0x4000C161, 0x00000102
#define BF_IRQ4_ASRCI_LOCKED_MASK_INFO           0x4000C161, 0x00000104
#define BF_IRQ4_ASRCI_UNLOCKED_MASK_INFO         0x4000C161, 0x00000105
#define BF_IRQ4_ASRCO_LOCKED_MASK_INFO           0x4000C161, 0x00000106
#define BF_IRQ4_ASRCO_UNLOCKED_MASK_INFO         0x4000C161, 0x00000107

#define REG_IRQ4_MASK3_ADDR                      0x4000C162
#define BF_IRQ4_SYNC_LOCKED_MASK_INFO            0x4000C162, 0x00000100
#define BF_IRQ4_SYNC_UNLOCKED_MASK_INFO          0x4000C162, 0x00000101
#define BF_IRQ4_SPT0_UNLOCKED_MASK_INFO          0x4000C162, 0x00000102
#define BF_IRQ4_SPT1_UNLOCKED_MASK_INFO          0x4000C162, 0x00000103
#define BF_IRQ4_POWER_UP_COMPLETE_MASK_INFO      0x4000C162, 0x00000104
#define BF_IRQ4_DLDO_DVS_DONE_MASK_INFO          0x4000C162, 0x00000105

#define REG_IRQ4_MASK4_ADDR                      0x4000C163
#define BF_IRQ4_SW_INT0_MASK_INFO                0x4000C163, 0x00000100
#define BF_IRQ4_SW_INT1_MASK_INFO                0x4000C163, 0x00000101
#define BF_IRQ4_SW_INT2_MASK_INFO                0x4000C163, 0x00000102
#define BF_IRQ4_SW_INT3_MASK_INFO                0x4000C163, 0x00000103
#define BF_IRQ4_DATA_SYNC_IRQ_MASK_INFO          0x4000C163, 0x00000104
#define BF_IRQ4_FFSRAM2_IRQ_MASK_INFO            0x4000C163, 0x00000105

#define REG_IRQ4_MASK5_ADDR                      0x4000C164
#define BF_IRQ4_TDSP_ERR_MASK_INFO               0x4000C164, 0x00000100
#define BF_IRQ4_AHB_ERR_MASK_INFO                0x4000C164, 0x00000101
#define BF_IRQ4_AHB_BUSY_MASK_INFO               0x4000C164, 0x00000102
#define BF_IRQ4_WDT_IRQ_MASK_INFO                0x4000C164, 0x00000103

#define REG_SW_INT_ADDR                          0x4000C165
#define BF_SW_INT0_INFO                          0x4000C165, 0x00000100
#define BF_SW_INT1_INFO                          0x4000C165, 0x00000101
#define BF_SW_INT2_INFO                          0x4000C165, 0x00000102
#define BF_SW_INT3_INFO                          0x4000C165, 0x00000103

#define REG_MP_INPUT_IRQ_CTRL1_ADDR              0x4000C168
#define BF_MP_INPUT_IRQ1_CLEAR_INFO              0x4000C168, 0x00000100
#define BF_MP_INPUT_IRQ2_CLEAR_INFO              0x4000C168, 0x00000101
#define BF_MP_INPUT_IRQ3_CLEAR_INFO              0x4000C168, 0x00000102

#define REG_MP_INPUT_IRQ_CTRL2_ADDR              0x4000C169
#define BF_MP_INPUT_IRQ1_MODE_INFO               0x4000C169, 0x00000200
#define BF_MP_INPUT_IRQ2_MODE_INFO               0x4000C169, 0x00000202
#define BF_MP_INPUT_IRQ3_MODE_INFO               0x4000C169, 0x00000204

#define REG_MP_INPUT_IRQ1_MASK1_ADDR             0x4000C16A
#define BF_MP_INPUT_IRQ1_MASK_INFO               0x4000C16A, 0x00001A00

#define REG_MP_INPUT_IRQ1_MASK2_ADDR             0x4000C16B

#define REG_MP_INPUT_IRQ1_MASK3_ADDR             0x4000C16C

#define REG_MP_INPUT_IRQ1_MASK4_ADDR             0x4000C16D

#define REG_MP_INPUT_IRQ2_MASK1_ADDR             0x4000C16E
#define BF_MP_INPUT_IRQ2_MASK_INFO               0x4000C16E, 0x00001A00

#define REG_MP_INPUT_IRQ2_MASK2_ADDR             0x4000C16F

#define REG_MP_INPUT_IRQ2_MASK3_ADDR             0x4000C170

#define REG_MP_INPUT_IRQ2_MASK4_ADDR             0x4000C171

#define REG_MP_INPUT_IRQ3_MASK1_ADDR             0x4000C172
#define BF_MP_INPUT_IRQ3_MASK_INFO               0x4000C172, 0x00001A00

#define REG_MP_INPUT_IRQ3_MASK2_ADDR             0x4000C173

#define REG_MP_INPUT_IRQ3_MASK3_ADDR             0x4000C174

#define REG_MP_INPUT_IRQ3_MASK4_ADDR             0x4000C175

#define REG_DUMMY0_ADDR                          0x4000C1C0
#define BF_DUMMY0_INFO                           0x4000C1C0, 0x00000800

#define REG_DUMMY1_ADDR                          0x4000C1C1
#define BF_DUMMY1_INFO                           0x4000C1C1, 0x00000800

#define REG_DUMMY2_ADDR                          0x4000C1C2
#define BF_DUMMY2_INFO                           0x4000C1C2, 0x00000800

#define REG_DUMMY3_ADDR                          0x4000C1C3
#define BF_DUMMY3_INFO                           0x4000C1C3, 0x00000800

#define REG_DUMMY4_ADDR                          0x4000C1C4
#define BF_DUMMY4_INFO                           0x4000C1C4, 0x00000800

#define REG_DUMMY5_ADDR                          0x4000C1C5
#define BF_DUMMY5_INFO                           0x4000C1C5, 0x00000800

#define REG_DUMMY6_ADDR                          0x4000C1C6
#define BF_DUMMY6_INFO                           0x4000C1C6, 0x00000800

#define REG_DUMMY7_ADDR                          0x4000C1C7
#define BF_DUMMY7_INFO                           0x4000C1C7, 0x00000800

#define REG_DUMMY8_ADDR                          0x4000C1C8
#define BF_DUMMY8_INFO                           0x4000C1C8, 0x00000800

#define REG_DUMMY9_ADDR                          0x4000C1C9
#define BF_DUMMY9_INFO                           0x4000C1C9, 0x00000800

#define REG_DUMMY10_ADDR                         0x4000C1CA
#define BF_DUMMY10_INFO                          0x4000C1CA, 0x00000800

#define REG_DUMMY11_ADDR                         0x4000C1CB
#define BF_DUMMY11_INFO                          0x4000C1CB, 0x00000800

#define REG_DUMMY12_ADDR                         0x4000C1CC
#define BF_DUMMY12_INFO                          0x4000C1CC, 0x00000800

#define REG_DUMMY13_ADDR                         0x4000C1CD
#define BF_DUMMY13_INFO                          0x4000C1CD, 0x00000800

#define REG_DUMMY14_ADDR                         0x4000C1CE
#define BF_DUMMY14_INFO                          0x4000C1CE, 0x00000800

#define REG_DUMMY15_ADDR                         0x4000C1CF
#define BF_DUMMY15_INFO                          0x4000C1CF, 0x00000800

#define REG_FDSP_MODE_ADDR                       0x4000C1D0
#define BF_FDSP_MODE_INFO                        0x4000C1D0, 0x00000100

#define REG_RESETS_ADDR                          0x4000C200
#define BF_SOFT_FULL_RESET_INFO                  0x4000C200, 0x00000100
#define BF_SOFT_RESET_INFO                       0x4000C200, 0x00000104

#define REG_READ_LAMBDA_ADDR                     0x4000C400
#define BF_FDSP_CURRENT_LAMBDA_INFO              0x4000C400, 0x00000600

#define REG_STATUS1_ADDR                         0x4000C401
#define BF_DAC0_CLIP_INFO                        0x4000C401, 0x00000100
#define BF_ADC0_CLIP_INFO                        0x4000C401, 0x00000101
#define BF_ADC1_CLIP_INFO                        0x4000C401, 0x00000102
#define BF_ADC2_CLIP_INFO                        0x4000C401, 0x00000103
#define BF_AVDD_UVW_INFO                         0x4000C401, 0x00000104

#define REG_STATUS2_ADDR                         0x4000C402
#define BF_PLL_LOCK_INFO                         0x4000C402, 0x00000100
#define BF_FM_CLK_READY_INFO                     0x4000C402, 0x00000101
#define BF_ASRCI_LOCK_INFO                       0x4000C402, 0x00000102
#define BF_ASRCO_LOCK_INFO                       0x4000C402, 0x00000103
#define BF_SPT0_LOCK_INFO                        0x4000C402, 0x00000104
#define BF_SPT1_LOCK_INFO                        0x4000C402, 0x00000105
#define BF_SYNC_LOCK_INFO                        0x4000C402, 0x00000106
#define BF_POWER_UP_COMPLETE_INFO                0x4000C402, 0x00000107

#define REG_SELFBOOT_STATUS_ADDR                 0x4000C403
#define BF_SELFBOOT_INFO                         0x4000C403, 0x00000100
#define BF_SELFBOOT_UNPACK_MODE_INFO             0x4000C403, 0x00000101

#define REG_EQ_STATUS_ADDR                       0x4000C404
#define BF_EQ_CLEAR_DONE_INFO                    0x4000C404, 0x00000100

#define REG_FDSP_STATUS_ADDR                     0x4000C405
#define BF_FDSP_MASK_ONZ_INFO                    0x4000C405, 0x00000100
#define BF_FDSP_BANK_COPY_DONE_INFO              0x4000C405, 0x00000104

#define REG_PMU_STATUS1_ADDR                     0x4000C406
#define BF_POWER_MODE_STA_INFO                   0x4000C406, 0x00000200
#define BF_MEM_VOLT_STA_INFO                     0x4000C406, 0x00000202
#define BF_DLDO_SCALE_BUSY_INFO                  0x4000C406, 0x00000104
#define BF_DLDO_DVS_DONE_INFO                    0x4000C406, 0x00000105
#define BF_STARTUP_DLYCNT_DONE_INFO              0x4000C406, 0x00000107

#define REG_PMU_STATUS2_ADDR                     0x4000C407
#define BF_ADP_MEM_DEEPSLEEP_INFO                0x4000C407, 0x00000100
#define BF_SOC_MEM_DEEPSLEEP_INFO                0x4000C407, 0x00000102

#define REG_PMU_STATUS3_ADDR                     0x4000C408
#define BF_ADP_MEM_SHUTDOWN_INFO                 0x4000C408, 0x00000300

#define REG_PMU_STATUS4_ADDR                     0x4000C409
#define BF_SOC_MEM_SHUTDOWN_INFO                 0x4000C409, 0x00000700

#define REG_TDSP_MODE_STATUS_ADDR                0x4000C40A
#define BF_TDSP_PWAIT_MODE_INFO                  0x4000C40A, 0x00000100
#define BF_TDSP_IRAM0_LDST_INFO                  0x4000C40A, 0x00000101
#define BF_TDSP_XOCD_MODE_INFO                   0x4000C40A, 0x00000102
#define BF_TDSP_DBG_MODE_INFO                    0x4000C40A, 0x00000103

#define REG_TDSP_ERROR_STATUS_ADDR               0x4000C40B
#define BF_TDSP_DOUB_EXCP_TDSP_ERROR_STATUS_INFO 0x4000C40B, 0x00000100
#define BF_TDSP_PFATAL_ERROR_INFO                0x4000C40B, 0x00000101

#define REG_TDSP_FAULT_INFO1_ADDR                0x4000C40C
#define BF_TDSP_PFAULT_INFO_INFO                 0x4000C40C, 0x00002000

#define REG_TDSP_FAULT_INFO2_ADDR                0x4000C40D

#define REG_TDSP_FAULT_INFO3_ADDR                0x4000C40E

#define REG_TDSP_FAULT_INFO4_ADDR                0x4000C40F

#define REG_TDSP_GPO1_ADDR                       0x4000C410
#define BF_TDSP_GPO_INFO                         0x4000C410, 0x00002000

#define REG_TDSP_GPO2_ADDR                       0x4000C411

#define REG_TDSP_GPO3_ADDR                       0x4000C412

#define REG_TDSP_GPO4_ADDR                       0x4000C413

#define REG_IRQ1_STATUS1_ADDR                    0x4000C414
#define BF_IRQ1_DAC0_CLIP_INFO                   0x4000C414, 0x00000100
#define BF_IRQ1_ADC0_CLIP_INFO                   0x4000C414, 0x00000101
#define BF_IRQ1_ADC1_CLIP_INFO                   0x4000C414, 0x00000102
#define BF_IRQ1_ADC2_CLIP_INFO                   0x4000C414, 0x00000103
#define BF_IRQ1_PLL_LOCKED_INFO                  0x4000C414, 0x00000104
#define BF_IRQ1_PLL_UNLOCKED_INFO                0x4000C414, 0x00000105
#define BF_IRQ1_AVDD_UVW_INFO                    0x4000C414, 0x00000106

#define REG_IRQ1_STATUS2_ADDR                    0x4000C415
#define BF_IRQ1_PRAMP_INFO                       0x4000C415, 0x00000100
#define BF_IRQ1_FDSP_MASK_ONZ_INFO               0x4000C415, 0x00000101
#define BF_IRQ1_EQ_CLEAR_DONE_INFO               0x4000C415, 0x00000102
#define BF_IRQ1_ASRCI_LOCKED_INFO                0x4000C415, 0x00000104
#define BF_IRQ1_ASRCI_UNLOCKED_INFO              0x4000C415, 0x00000105
#define BF_IRQ1_ASRCO_LOCKED_INFO                0x4000C415, 0x00000106
#define BF_IRQ1_ASRCO_UNLOCKED_INFO              0x4000C415, 0x00000107

#define REG_IRQ1_STATUS3_ADDR                    0x4000C416
#define BF_IRQ1_SYNC_LOCKED_INFO                 0x4000C416, 0x00000100
#define BF_IRQ1_SYNC_UNLOCKED_INFO               0x4000C416, 0x00000101
#define BF_IRQ1_SPT0_UNLOCKED_INFO               0x4000C416, 0x00000102
#define BF_IRQ1_SPT1_UNLOCKED_INFO               0x4000C416, 0x00000103
#define BF_IRQ1_POWER_UP_COMPLETE_INFO           0x4000C416, 0x00000104
#define BF_IRQ1_DLDO_DVS_DONE_INFO               0x4000C416, 0x00000105

#define REG_IRQ1_STATUS4_ADDR                    0x4000C417
#define BF_IRQ1_SW_INT0_INFO                     0x4000C417, 0x00000100
#define BF_IRQ1_SW_INT1_INFO                     0x4000C417, 0x00000101
#define BF_IRQ1_SW_INT2_INFO                     0x4000C417, 0x00000102
#define BF_IRQ1_SW_INT3_INFO                     0x4000C417, 0x00000103
#define BF_IRQ1_DATA_SYNC_IRQ_INFO               0x4000C417, 0x00000104
#define BF_IRQ1_FFSRAM2_IRQ_INFO                 0x4000C417, 0x00000105

#define REG_IRQ1_STATUS5_ADDR                    0x4000C418
#define BF_IRQ1_TDSP_ERR_INFO                    0x4000C418, 0x00000100
#define BF_IRQ1_AHB_ERR_INFO                     0x4000C418, 0x00000101
#define BF_IRQ1_AHB_BUSY_INFO                    0x4000C418, 0x00000102
#define BF_IRQ1_WDT_IRQ_INFO                     0x4000C418, 0x00000103

#define REG_IRQ2_STATUS1_ADDR                    0x4000C419
#define BF_IRQ2_DAC0_CLIP_INFO                   0x4000C419, 0x00000100
#define BF_IRQ2_ADC0_CLIP_INFO                   0x4000C419, 0x00000101
#define BF_IRQ2_ADC1_CLIP_INFO                   0x4000C419, 0x00000102
#define BF_IRQ2_ADC2_CLIP_INFO                   0x4000C419, 0x00000103
#define BF_IRQ2_PLL_LOCKED_INFO                  0x4000C419, 0x00000104
#define BF_IRQ2_PLL_UNLOCKED_INFO                0x4000C419, 0x00000105
#define BF_IRQ2_AVDD_UVW_INFO                    0x4000C419, 0x00000106

#define REG_IRQ2_STATUS2_ADDR                    0x4000C41A
#define BF_IRQ2_PRAMP_INFO                       0x4000C41A, 0x00000100
#define BF_IRQ2_FDSP_MASK_ONZ_INFO               0x4000C41A, 0x00000101
#define BF_IRQ2_EQ_CLEAR_DONE_INFO               0x4000C41A, 0x00000102
#define BF_IRQ2_ASRCI_LOCKED_INFO                0x4000C41A, 0x00000104
#define BF_IRQ2_ASRCI_UNLOCKED_INFO              0x4000C41A, 0x00000105
#define BF_IRQ2_ASRCO_LOCKED_INFO                0x4000C41A, 0x00000106
#define BF_IRQ2_ASRCO_UNLOCKED_INFO              0x4000C41A, 0x00000107

#define REG_IRQ2_STATUS3_ADDR                    0x4000C41B
#define BF_IRQ2_SYNC_LOCKED_INFO                 0x4000C41B, 0x00000100
#define BF_IRQ2_SYNC_UNLOCKED_INFO               0x4000C41B, 0x00000101
#define BF_IRQ2_SPT0_UNLOCKED_INFO               0x4000C41B, 0x00000102
#define BF_IRQ2_SPT1_UNLOCKED_INFO               0x4000C41B, 0x00000103
#define BF_IRQ2_POWER_UP_COMPLETE_INFO           0x4000C41B, 0x00000104
#define BF_IRQ2_DLDO_DVS_DONE_INFO               0x4000C41B, 0x00000105

#define REG_IRQ2_STATUS4_ADDR                    0x4000C41C
#define BF_IRQ2_SW_INT0_INFO                     0x4000C41C, 0x00000100
#define BF_IRQ2_SW_INT1_INFO                     0x4000C41C, 0x00000101
#define BF_IRQ2_SW_INT2_INFO                     0x4000C41C, 0x00000102
#define BF_IRQ2_SW_INT3_INFO                     0x4000C41C, 0x00000103
#define BF_IRQ2_DATA_SYNC_IRQ_INFO               0x4000C41C, 0x00000104
#define BF_IRQ2_FFSRAM2_IRQ_INFO                 0x4000C41C, 0x00000105

#define REG_IRQ2_STATUS5_ADDR                    0x4000C41D
#define BF_IRQ2_TDSP_ERR_INFO                    0x4000C41D, 0x00000100
#define BF_IRQ2_AHB_ERR_INFO                     0x4000C41D, 0x00000101
#define BF_IRQ2_AHB_BUSY_INFO                    0x4000C41D, 0x00000102
#define BF_IRQ2_WDT_IRQ_INFO                     0x4000C41D, 0x00000103

#define REG_IRQ3_STATUS1_ADDR                    0x4000C41E
#define BF_IRQ3_DAC0_CLIP_INFO                   0x4000C41E, 0x00000100
#define BF_IRQ3_ADC0_CLIP_INFO                   0x4000C41E, 0x00000101
#define BF_IRQ3_ADC1_CLIP_INFO                   0x4000C41E, 0x00000102
#define BF_IRQ3_ADC2_CLIP_INFO                   0x4000C41E, 0x00000103
#define BF_IRQ3_PLL_LOCKED_INFO                  0x4000C41E, 0x00000104
#define BF_IRQ3_PLL_UNLOCKED_INFO                0x4000C41E, 0x00000105
#define BF_IRQ3_AVDD_UVW_INFO                    0x4000C41E, 0x00000106

#define REG_IRQ3_STATUS2_ADDR                    0x4000C41F
#define BF_IRQ3_PRAMP_INFO                       0x4000C41F, 0x00000100
#define BF_IRQ3_FDSP_MASK_ONZ_INFO               0x4000C41F, 0x00000101
#define BF_IRQ3_EQ_CLEAR_DONE_INFO               0x4000C41F, 0x00000102
#define BF_IRQ3_ASRCI_LOCKED_INFO                0x4000C41F, 0x00000104
#define BF_IRQ3_ASRCI_UNLOCKED_INFO              0x4000C41F, 0x00000105
#define BF_IRQ3_ASRCO_LOCKED_INFO                0x4000C41F, 0x00000106
#define BF_IRQ3_ASRCO_UNLOCKED_INFO              0x4000C41F, 0x00000107

#define REG_IRQ3_STATUS3_ADDR                    0x4000C420
#define BF_IRQ3_SYNC_LOCKED_INFO                 0x4000C420, 0x00000100
#define BF_IRQ3_SYNC_UNLOCKED_INFO               0x4000C420, 0x00000101
#define BF_IRQ3_SPT0_UNLOCKED_INFO               0x4000C420, 0x00000102
#define BF_IRQ3_SPT1_UNLOCKED_INFO               0x4000C420, 0x00000103
#define BF_IRQ3_POWER_UP_COMPLETE_INFO           0x4000C420, 0x00000104
#define BF_IRQ3_DLDO_DVS_DONE_INFO               0x4000C420, 0x00000105

#define REG_IRQ3_STATUS4_ADDR                    0x4000C421
#define BF_IRQ3_SW_INT0_INFO                     0x4000C421, 0x00000100
#define BF_IRQ3_SW_INT1_INFO                     0x4000C421, 0x00000101
#define BF_IRQ3_SW_INT2_INFO                     0x4000C421, 0x00000102
#define BF_IRQ3_SW_INT3_INFO                     0x4000C421, 0x00000103
#define BF_IRQ3_DATA_SYNC_IRQ_INFO               0x4000C421, 0x00000104
#define BF_IRQ3_FFSRAM2_IRQ_INFO                 0x4000C421, 0x00000105

#define REG_IRQ3_STATUS5_ADDR                    0x4000C422
#define BF_IRQ3_TDSP_ERR_INFO                    0x4000C422, 0x00000100
#define BF_IRQ3_AHB_ERR_INFO                     0x4000C422, 0x00000101
#define BF_IRQ3_AHB_BUSY_INFO                    0x4000C422, 0x00000102
#define BF_IRQ3_WDT_IRQ_INFO                     0x4000C422, 0x00000103

#define REG_IRQ4_STATUS1_ADDR                    0x4000C423
#define BF_IRQ4_DAC0_CLIP_INFO                   0x4000C423, 0x00000100
#define BF_IRQ4_ADC0_CLIP_INFO                   0x4000C423, 0x00000101
#define BF_IRQ4_ADC1_CLIP_INFO                   0x4000C423, 0x00000102
#define BF_IRQ4_ADC2_CLIP_INFO                   0x4000C423, 0x00000103
#define BF_IRQ4_PLL_LOCKED_INFO                  0x4000C423, 0x00000104
#define BF_IRQ4_PLL_UNLOCKED_INFO                0x4000C423, 0x00000105
#define BF_IRQ4_AVDD_UVW_INFO                    0x4000C423, 0x00000106

#define REG_IRQ4_STATUS2_ADDR                    0x4000C424
#define BF_IRQ4_PRAMP_INFO                       0x4000C424, 0x00000100
#define BF_IRQ4_FDSP_MASK_ONZ_INFO               0x4000C424, 0x00000101
#define BF_IRQ4_EQ_CLEAR_DONE_INFO               0x4000C424, 0x00000102
#define BF_IRQ4_ASRCI_LOCKED_INFO                0x4000C424, 0x00000104
#define BF_IRQ4_ASRCI_UNLOCKED_INFO              0x4000C424, 0x00000105
#define BF_IRQ4_ASRCO_LOCKED_INFO                0x4000C424, 0x00000106
#define BF_IRQ4_ASRCO_UNLOCKED_INFO              0x4000C424, 0x00000107

#define REG_IRQ4_STATUS3_ADDR                    0x4000C425
#define BF_IRQ4_SYNC_LOCKED_INFO                 0x4000C425, 0x00000100
#define BF_IRQ4_SYNC_UNLOCKED_INFO               0x4000C425, 0x00000101
#define BF_IRQ4_SPT0_UNLOCKED_INFO               0x4000C425, 0x00000102
#define BF_IRQ4_SPT1_UNLOCKED_INFO               0x4000C425, 0x00000103
#define BF_IRQ4_POWER_UP_COMPLETE_INFO           0x4000C425, 0x00000104
#define BF_IRQ4_DLDO_DVS_DONE_INFO               0x4000C425, 0x00000105

#define REG_IRQ4_STATUS4_ADDR                    0x4000C426
#define BF_IRQ4_SW_INT0_INFO                     0x4000C426, 0x00000100
#define BF_IRQ4_SW_INT1_INFO                     0x4000C426, 0x00000101
#define BF_IRQ4_SW_INT2_INFO                     0x4000C426, 0x00000102
#define BF_IRQ4_SW_INT3_INFO                     0x4000C426, 0x00000103
#define BF_IRQ4_DATA_SYNC_IRQ_INFO               0x4000C426, 0x00000104
#define BF_IRQ4_FFSRAM2_IRQ_INFO                 0x4000C426, 0x00000105

#define REG_IRQ4_STATUS5_ADDR                    0x4000C427
#define BF_IRQ4_TDSP_ERR_INFO                    0x4000C427, 0x00000100
#define BF_IRQ4_AHB_ERR_INFO                     0x4000C427, 0x00000101
#define BF_IRQ4_AHB_BUSY_INFO                    0x4000C427, 0x00000102
#define BF_IRQ4_WDT_IRQ_INFO                     0x4000C427, 0x00000103

#define REG_MP_INPUT_IRQ1_STATUS1_ADDR           0x4000C428
#define BF_MP_INPUT_IRQ1_STATUS_INFO             0x4000C428, 0x00001A00

#define REG_MP_INPUT_IRQ1_STATUS2_ADDR           0x4000C429

#define REG_MP_INPUT_IRQ1_STATUS3_ADDR           0x4000C42A

#define REG_MP_INPUT_IRQ1_STATUS4_ADDR           0x4000C42B

#define REG_MP_INPUT_IRQ2_STATUS1_ADDR           0x4000C42C
#define BF_MP_INPUT_IRQ2_STATUS_INFO             0x4000C42C, 0x00001A00

#define REG_MP_INPUT_IRQ2_STATUS2_ADDR           0x4000C42D

#define REG_MP_INPUT_IRQ2_STATUS3_ADDR           0x4000C42E

#define REG_MP_INPUT_IRQ2_STATUS4_ADDR           0x4000C42F

#define REG_MP_INPUT_IRQ3_STATUS1_ADDR           0x4000C430
#define BF_MP_INPUT_IRQ3_IRQ_STATUS_INFO         0x4000C430, 0x00001A00

#define REG_MP_INPUT_IRQ3_STATUS2_ADDR           0x4000C431

#define REG_MP_INPUT_IRQ3_STATUS3_ADDR           0x4000C432

#define REG_MP_INPUT_IRQ3_STATUS4_ADDR           0x4000C433

#define REG_GPI1_ADDR                            0x4000C434
#define BF_GPIO0_IN_INFO                         0x4000C434, 0x00000100
#define BF_GPIO1_IN_INFO                         0x4000C434, 0x00000101
#define BF_GPIO2_IN_INFO                         0x4000C434, 0x00000102
#define BF_GPIO3_IN_INFO                         0x4000C434, 0x00000103
#define BF_GPIO4_IN_INFO                         0x4000C434, 0x00000104
#define BF_GPIO5_IN_INFO                         0x4000C434, 0x00000105
#define BF_GPIO6_IN_INFO                         0x4000C434, 0x00000106
#define BF_GPIO7_IN_INFO                         0x4000C434, 0x00000107

#define REG_GPI2_ADDR                            0x4000C435
#define BF_GPIO8_IN_INFO                         0x4000C435, 0x00000100
#define BF_GPIO9_IN_INFO                         0x4000C435, 0x00000101
#define BF_GPIO10_IN_INFO                        0x4000C435, 0x00000102
#define BF_GPIO11_IN_INFO                        0x4000C435, 0x00000103
#define BF_GPIO12_IN_INFO                        0x4000C435, 0x00000104
#define BF_GPIO13_IN_INFO                        0x4000C435, 0x00000105
#define BF_GPIO14_IN_INFO                        0x4000C435, 0x00000106
#define BF_GPIO15_IN_INFO                        0x4000C435, 0x00000107

#define REG_GPI3_ADDR                            0x4000C436
#define BF_GPIO16_IN_INFO                        0x4000C436, 0x00000100
#define BF_GPIO17_IN_INFO                        0x4000C436, 0x00000101
#define BF_GPIO18_IN_INFO                        0x4000C436, 0x00000102
#define BF_GPIO19_IN_INFO                        0x4000C436, 0x00000103
#define BF_GPIO20_IN_INFO                        0x4000C436, 0x00000104
#define BF_GPIO21_IN_INFO                        0x4000C436, 0x00000105
#define BF_GPIO22_IN_INFO                        0x4000C436, 0x00000106
#define BF_GPIO23_IN_INFO                        0x4000C436, 0x00000107

#define REG_GPI4_ADDR                            0x4000C437
#define BF_GPIO24_IN_INFO                        0x4000C437, 0x00000100
#define BF_GPIO25_IN_INFO                        0x4000C437, 0x00000101

#define REG_CTRL_PORT_MODE_ADDR                  0x4000C438
#define BF_CTRL_PORT_MODE_INFO                   0x4000C438, 0x00000200

#define REG_DAC_NOISE_CTRL2_ADDR                 0x4000CC04
#define BF_DAC_LOW_NOISE_EN2_INFO                0x4000CC04, 0x00000101

#define REG_DAC_NOISE_CTRL1_ADDR                 0x4000CC12
#define BF_DAC_LOW_NOISE_EN1_INFO                0x4000CC12, 0x00000104

#define REG_HOLD_TIME_ADJ_ADDR                   0x4000CC32

#define REG_PMU_TEST3_ADDR                       0x4000CC35

#define REG_PMU_TEST5_ADDR                       0x4000CC37

#define REG_PMU_TEST8_ADDR                       0x4000CC3A

#define REG_PMU_TEST10_ADDR                      0x4000CC3C

#define REG_PMU_TEST13_ADDR                      0x4000CC3F

#define REG_PMU_TEST15_ADDR                      0x4000CC41

#define REG_DUMMY_SPI_ENABLE_ADDR                0x4000CCFF

#define REG_SW_EN_CTRL_ADDR                      0x4000CD00
#define BF_SWEN_DRIVE_INFO                       0x4000CD00, 0x00000200
#define BF_SWEN_PULL_EN_INFO                     0x4000CD00, 0x00000104
#define BF_SWEN_PULL_SEL_INFO                    0x4000CD00, 0x00000105
#define BF_SWEN_SLEW_INFO                        0x4000CD00, 0x00000106

#define REG_MBIAS_CTRL_ADDR                      0x4000CD01
#define BF_MBIAS0_LEVEL_INFO                     0x4000CD01, 0x00000100
#define BF_MBIAS1_LEVEL_INFO                     0x4000CD01, 0x00000101
#define BF_MBIAS_IBIAS_INFO                      0x4000CD01, 0x00000204

#define REG_NONCE_1_ADDR                         0x4000CDB3

#define REG_AUTH_CHALLENGE_1_ADDR                0x4000CDB5

#define REG_AUTH_CHALLENGE_2_ADDR                0x4000CDB6

#define REG_AUTH_RESPONSE_1_ADDR                 0x4000CDB8

#define REG_AUTH_RESPONSE_2_ADDR                 0x4000CDB9

#define REG_READBACK_KEY_1_ADDR                  0x4000CDBB

#define REG_READBACK_KEY_2_ADDR                  0x4000CDBC

#define REG_READBACK_KEY_3_ADDR                  0x4000CDBD

#define REG_READBACK_KEY_4_ADDR                  0x4000CDBE

#define REG_READBACK_KEY_5_ADDR                  0x4000CDBF

#define REG_READBACK_KEY_6_ADDR                  0x4000CDC0

#define REG_READBACK_KEY_7_ADDR                  0x4000CDC1

#define REG_READBACK_KEY_8_ADDR                  0x4000CDC2

#define REG_READBACK_KEY_9_ADDR                  0x4000CDC3

#define REG_READBACK_KEY_10_ADDR                 0x4000CDC4

#define REG_READBACK_KEY_11_ADDR                 0x4000CDC5

#define REG_READBACK_KEY_12_ADDR                 0x4000CDC6

#define REG_READBACK_KEY_13_ADDR                 0x4000CDC7

#define REG_READBACK_KEY_14_ADDR                 0x4000CDC8

#define REG_READBACK_KEY_15_ADDR                 0x4000CDC9

#endif /* __ADI_LARK_BF_LARK_YODA_H__ */
/*! @} */
