/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.1 at 7/5/2021 7:01:27 AM.
 * 
 * @copyright copyright(c) 2018 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup LARK_BF
 * @{
 */
#ifndef __ADI_LARK_BF_QSPI_H__
#define __ADI_LARK_BF_QSPI_H__

/*============= D E F I N E S ==============*/

#define REG_QSPI_CTRL_ADDR                           0x40001004
#define BF_QSPI_EN_INFO                              0x40001004, 0x00000100
#define BF_QSPI_MASTER_INFO                          0x40001004, 0x00000101
#define BF_QSPI_CS_PROT_EN_INFO                      0x40001004, 0x00000102
#define BF_QSPI_OPEN_DRAIN_INFO                      0x40001004, 0x00000103
#define BF_QSPI_CPHA_INFO                            0x40001004, 0x00000104
#define BF_QSPI_CPOL_INFO                            0x40001004, 0x00000105
#define BF_QSPI_CS_CTRL_INFO                         0x40001004, 0x00000106
#define BF_QSPI_CS_POL_IN_TRAN_INFO                  0x40001004, 0x00000107
#define BF_QSPI_MISO_EN_INFO                         0x40001004, 0x00000108
#define BF_QSPI_SIZE_INFO                            0x40001004, 0x00000209
#define BF_QSPI_LSB_FIRST_INFO                       0x40001004, 0x0000010C
#define BF_QSPI_FLOW_CTRL_EN_INFO                    0x40001004, 0x0000010D
#define BF_QSPI_FLOW_CTRL_CHSEL_INFO                 0x40001004, 0x0000010E
#define BF_QSPI_FLOW_CTRL_POL_INFO                   0x40001004, 0x0000010F
#define BF_QSPI_FLOW_CTRL_WATERMARK_INFO             0x40001004, 0x00000210
#define BF_QSPI_FAST_MODE_INFO                       0x40001004, 0x00000112
#define BF_QSPI_MULTI_IO_INFO                        0x40001004, 0x00000214
#define BF_QSPI_MULTI_IO_ORDER_INFO                  0x40001004, 0x00000116
#define BF_QSPI_MEMMAP_RD_ERR_MASK_INFO              0x40001004, 0x0000011D
#define BF_QSPI_MEMMAP_WR_ERR_MASK_INFO              0x40001004, 0x0000011E
#define BF_QSPI_MEMMAP_EN_INFO                       0x40001004, 0x0000011F

#define REG_QSPI_RX_CTRL_ADDR                        0x40001008
#define BF_QSPI_RX_EN_INFO                           0x40001008, 0x00000100
#define BF_QSPI_RX_INIT_INFO                         0x40001008, 0x00000102
#define BF_QSPI_RX_WCNT_EN_INFO                      0x40001008, 0x00000103
#define BF_QSPI_RXD_REQ_INFO                         0x40001008, 0x00000304
#define BF_QSPI_RXD_OVRUN_INFO                       0x40001008, 0x00000108
#define BF_QSPI_RXFF_REG_WM_INFO                     0x40001008, 0x0000020C
#define BF_QSPI_RXFF_URG_WM_INFO                     0x40001008, 0x00000310

#define REG_QSPI_TX_CTRL_ADDR                        0x4000100C
#define BF_QSPI_TX_EN_INFO                           0x4000100C, 0x00000100
#define BF_QSPI_TX_INIT_INFO                         0x4000100C, 0x00000102
#define BF_QSPI_TX_WCNT_EN_INFO                      0x4000100C, 0x00000103
#define BF_QSPI_TXD_REQ_INFO                         0x4000100C, 0x00000304
#define BF_QSPI_TXD_UDRUN_INFO                       0x4000100C, 0x00000108
#define BF_QSPI_TXFF_REG_WM_INFO                     0x4000100C, 0x0000020C
#define BF_QSPI_TXFF_URG_WM_INFO                     0x4000100C, 0x00000310

#define REG_QSPI_CLK_CTRL_ADDR                       0x40001010
#define BF_QSPI_CLK_RATIO_INFO                       0x40001010, 0x00001000

#define REG_QSPI_DLY_ADDR                            0x40001014
#define BF_QSPI_DLY_VAL_INFO                         0x40001014, 0x00000800
#define BF_QSPI_EXT_LEAD_EN_INFO                     0x40001014, 0x00000108
#define BF_QSPI_EXT_LAG_EN_INFO                      0x40001014, 0x00000109

#define REG_QSPI_SLV_SEL_ADDR                        0x40001018
#define BF_QSPI_SSEL1_EN_INFO                        0x40001018, 0x00000101
#define BF_QSPI_SSEL2_EN_INFO                        0x40001018, 0x00000102
#define BF_QSPI_SSEL3_EN_INFO                        0x40001018, 0x00000103
#define BF_QSPI_SSEL4_EN_INFO                        0x40001018, 0x00000104
#define BF_QSPI_SSEL5_EN_INFO                        0x40001018, 0x00000105
#define BF_QSPI_SSEL6_EN_INFO                        0x40001018, 0x00000106
#define BF_QSPI_SSEL7_EN_INFO                        0x40001018, 0x00000107
#define BF_QSPI_SSEL1_INFO                           0x40001018, 0x00000109
#define BF_QSPI_SSEL2_INFO                           0x40001018, 0x0000010A
#define BF_QSPI_SSEL3_INFO                           0x40001018, 0x0000010B
#define BF_QSPI_SSEL4_INFO                           0x40001018, 0x0000010C
#define BF_QSPI_SSEL5_INFO                           0x40001018, 0x0000010D
#define BF_QSPI_SSEL6_INFO                           0x40001018, 0x0000010E
#define BF_QSPI_SSEL7_INFO                           0x40001018, 0x0000010F

#define REG_QSPI_RX_CNT_ADDR                         0x4000101C
#define BF_QSPI_RX_CNT_INFO                          0x4000101C, 0x00001000

#define REG_QSPI_RX_RLD_CNT_ADDR                     0x40001020
#define BF_QSPI_RX_RLD_CNT_INFO                      0x40001020, 0x00001000

#define REG_QSPI_TX_CNT_ADDR                         0x40001024
#define BF_QSPI_TX_CNT_INFO                          0x40001024, 0x00001000

#define REG_QSPI_TX_RLD_CNT_ADDR                     0x40001028
#define BF_QSPI_TX_RLD_CNT_INFO                      0x40001028, 0x00001000

#define REG_QSPI_INT_MASK_ADDR                       0x40001030
#define BF_QSPI_RX_URGWM_INTMASK_INFO                0x40001030, 0x00000101
#define BF_QSPI_TX_URGWM_INTMASK_INFO                0x40001030, 0x00000102
#define BF_QSPI_RX_OVRUN_INTMASK_INFO                0x40001030, 0x00000104
#define BF_QSPI_TX_UDRUN_INTMASK_INFO                0x40001030, 0x00000105
#define BF_QSPI_TX_COL_INTMASK_INFO                  0x40001030, 0x00000106
#define BF_QSPI_MODE_FAULT_INTMASK_INFO              0x40001030, 0x00000107
#define BF_QSPI_RX_START_INTMASK_INFO                0x40001030, 0x00000108
#define BF_QSPI_TX_START_INTMASK_INFO                0x40001030, 0x00000109
#define BF_QSPI_RX_DONE_INTMASK_INFO                 0x40001030, 0x0000010A
#define BF_QSPI_TX_DONE_INTMASK_INFO                 0x40001030, 0x0000010B

#define REG_QSPI_INT_MASK_CLR_ADDR                   0x40001034
#define BF_QSPI_RX_URGWM_INTMASK_CLR_INFO            0x40001034, 0x00000101
#define BF_QSPI_TX_URGWM_INTMASK_CLR_INFO            0x40001034, 0x00000102
#define BF_QSPI_RX_OVRUN_INTMASK_CLR_INFO            0x40001034, 0x00000104
#define BF_QSPI_TX_UDRUN_INTMASK_CLR_INFO            0x40001034, 0x00000105
#define BF_QSPI_TX_COL_INTMASK_CLR_INFO              0x40001034, 0x00000106
#define BF_QSPI_MODE_FAULT_INTMASK_CLR_INFO          0x40001034, 0x00000107
#define BF_QSPI_RX_START_INTMASK_CLR_INFO            0x40001034, 0x00000108
#define BF_QSPI_TX_START_INTMASK_CLR_INFO            0x40001034, 0x00000109
#define BF_QSPI_RX_DONE_INTMASK_CLR_INFO             0x40001034, 0x0000010A
#define BF_QSPI_TX_DONE_INTMASK_CLR_INFO             0x40001034, 0x0000010B

#define REG_QSPI_INT_MASK_SET_ADDR                   0x40001038
#define BF_QSPI_RX_URGWM_INTMASK_SET_INFO            0x40001038, 0x00000101
#define BF_QSPI_TX_URGWM_INTMASK_SET_INFO            0x40001038, 0x00000102
#define BF_QSPI_RX_OVRUN_INTMASK_SET_INFO            0x40001038, 0x00000104
#define BF_QSPI_TX_UDRUN_INTMASK_SET_INFO            0x40001038, 0x00000105
#define BF_QSPI_TX_COL_INTMASK_SET_INFO              0x40001038, 0x00000106
#define BF_QSPI_MODE_FAULT_INTMASK_SET_INFO          0x40001038, 0x00000107
#define BF_QSPI_RX_START_INTMASK_SET_INFO            0x40001038, 0x00000108
#define BF_QSPI_TX_START_INTMASK_SET_INFO            0x40001038, 0x00000109
#define BF_QSPI_RX_DONE_INTMASK_SET_INFO             0x40001038, 0x0000010A
#define BF_QSPI_TX_DONE_INTMASK_SET_INFO             0x40001038, 0x0000010B

#define REG_QSPI_STATUS_ADDR                         0x40001040
#define BF_QSPI_TRAN_DONE_INFO                       0x40001040, 0x00000100
#define BF_QSPI_RX_URGWM_INFO                        0x40001040, 0x00000101
#define BF_QSPI_TX_URGWM_INFO                        0x40001040, 0x00000102
#define BF_QSPI_RX_OVRUN_INFO                        0x40001040, 0x00000104
#define BF_QSPI_TX_UDRUN_INFO                        0x40001040, 0x00000105
#define BF_QSPI_TX_COL_INFO                          0x40001040, 0x00000106
#define BF_QSPI_MODE_FAULT_INFO                      0x40001040, 0x00000107
#define BF_QSPI_RX_START_INFO                        0x40001040, 0x00000108
#define BF_QSPI_TX_START_INFO                        0x40001040, 0x00000109
#define BF_QSPI_RX_DONE_INFO                         0x40001040, 0x0000010A
#define BF_QSPI_TX_DONE_INFO                         0x40001040, 0x0000010B
#define BF_QSPI_RX_FF_STATUS_QSPI_STATUS_INFO        0x40001040, 0x0000030C
#define BF_QSPI_TX_FF_STATUS_INFO                    0x40001040, 0x00000310
#define BF_QSPI_FLOW_CTRL_STATUS_INFO                0x40001040, 0x00000114
#define BF_QSPI_RX_FF_EMPTY_INFO                     0x40001040, 0x00000116
#define BF_QSPI_TX_FF_FULL_INFO                      0x40001040, 0x00000117
#define BF_QSPI_MEMMAP_WR_ERR_INFO                   0x40001040, 0x0000011C
#define BF_QSPI_MEMMAP_RD_ERR_INFO                   0x40001040, 0x0000011D
#define BF_QSPI_MEMMAP_FF_ERR_INFO                   0x40001040, 0x0000011F

#define REG_QSPI_INT_LATCH_ADDR                      0x40001044
#define BF_QSPI_RX_URGWM_LATCH_INFO                  0x40001044, 0x00000101
#define BF_QSPI_TX_URGWM_LATCH_INFO                  0x40001044, 0x00000102
#define BF_QSPI_RX_OVRUN_LATCH_INFO                  0x40001044, 0x00000104
#define BF_QSPI_TX_UDRUN_LATCH_INFO                  0x40001044, 0x00000105
#define BF_QSPI_TX_COL_LATCH_INFO                    0x40001044, 0x00000106
#define BF_QSPI_MODE_FAULT_LATCH_INFO                0x40001044, 0x00000107
#define BF_QSPI_RX_START_LATCH_INFO                  0x40001044, 0x00000108
#define BF_QSPI_TX_START_LATCH_INFO                  0x40001044, 0x00000109
#define BF_QSPI_RX_DONE_LATCH_INFO                   0x40001044, 0x0000010A
#define BF_QSPI_TX_DONE_LATCH_INFO                   0x40001044, 0x0000010B

#define REG_QSPI_INT_LATCH_CLR_ADDR                  0x40001048
#define BF_QSPI_RX_URGWM_LATCH_CLR_INFO              0x40001048, 0x00000101
#define BF_QSPI_TX_URGWM_LATCH_CLR_INFO              0x40001048, 0x00000102
#define BF_QSPI_RX_OVRUN_LATCH_CLR_INFO              0x40001048, 0x00000104
#define BF_QSPI_TX_UDRUN_LATCH_CLR_INFO              0x40001048, 0x00000105
#define BF_QSPI_TX_COL_LATCH_CLR_INFO                0x40001048, 0x00000106
#define BF_QSPI_MODE_FAULT_LATCH_CLR_INFO            0x40001048, 0x00000107
#define BF_QSPI_RX_START_LATCH_CLR_INFO              0x40001048, 0x00000108
#define BF_QSPI_TX_START_LATCH_CLR_INFO              0x40001048, 0x00000109
#define BF_QSPI_RX_DONE_LATCH_CLR_INFO               0x40001048, 0x0000010A
#define BF_QSPI_TX_DONE_LATCH_CLR_INFO               0x40001048, 0x0000010B
#define BF_QSPI_RX_FF_STATUS_QSPI_INT_LATCH_CLR_INFO 0x40001048, 0x0000030C

#define REG_QSPI_RX_FIFO_ADDR                        0x40001050
#define BF_QSPI_RX_DATA_INFO                         0x40001050, 0x00002000

#define REG_QSPI_TX_FIFO_ADDR                        0x40001058
#define BF_QSPI_TX_DATA_INFO                         0x40001058, 0x00002000

#define REG_QSPI_MMRD_HDR_ADDR                       0x40001060
#define BF_QSPI_MMRD_OP_CODE_INFO                    0x40001060, 0x00000800
#define BF_QSPI_MMRD_ADR_SIZE_INFO                   0x40001060, 0x00000308
#define BF_QSPI_MMRD_ADR_PINS_INFO                   0x40001060, 0x0000010B
#define BF_QSPI_MMRD_DMY_SIZE_INFO                   0x40001060, 0x0000030C
#define BF_QSPI_MMRD_MODE_INFO                       0x40001060, 0x00000810
#define BF_QSPI_MMRD_TRISTATE_DMY_INFO               0x40001060, 0x00000218
#define BF_QSPI_MMRD_MERGE_EN_INFO                   0x40001060, 0x0000011A
#define BF_QSPI_MMRD_WRAP_INFO                       0x40001060, 0x0000011B
#define BF_QSPI_MMRD_CMD_SKIP_EN_INFO                0x40001060, 0x0000011C
#define BF_QSPI_MMRD_CMD_PINS_INFO                   0x40001060, 0x0000011D

#define REG_QSPI_MEMTOP_ADR_ADDR                     0x40001064
#define BF_QSPI_MMRD_TOP_ADR_INFO                    0x40001064, 0x00002000

#endif /* __ADI_LARK_BF_QSPI_H__ */
/*! @} */
