/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.1 at 7/5/2021 7:01:27 AM.
 * 
 * @copyright copyright(c) 2018 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup LARK_BF
 * @{
 */
#ifndef __ADI_LARK_BF_SOC_H__
#define __ADI_LARK_BF_SOC_H__

/*============= D E F I N E S ==============*/
#define REG_SOC_CLKEN_ADDR                    0x40002000
#define BF_SOC_CLKEN_SYSRAM_INFO              0x40002000, 0x00000100
#define BF_SOC_CLKEN_FFSRAM0_INFO             0x40002000, 0x00000101
#define BF_SOC_CLKEN_FFSRAM1_INFO             0x40002000, 0x00000102
#define BF_SOC_CLKEN_QSPI_INFO                0x40002000, 0x00000103
#define BF_SOC_CLKEN_DMA_INFO                 0x40002000, 0x00000105
#define BF_SOC_CLKEN_UART_INFO                0x40002000, 0x00000110
#define BF_SOC_CLKEN_SPI_INFO                 0x40002000, 0x00000111
#define BF_SOC_CLKEN_GPT_INFO                 0x40002000, 0x00000112
#define BF_SOC_CLKEN_WDT_INFO                 0x40002000, 0x00000113
#define BF_SOC_CLKEN_SOC2AON_INFO             0x40002000, 0x00000114

#define REG_SOC_DUMMY1_ADDR                   0x40002004
#define BF_SOC_DUMMY1_INFO                    0x40002004, 0x00002000

#define REG_SOC_DUMMY2_ADDR                   0x40002008
#define BF_SOC_DUMMY2_INFO                    0x40002008, 0x00002000

#define REG_SOC_DUMMY3_ADDR                   0x4000200C
#define BF_SOC_DUMMY3_INFO                    0x4000200C, 0x00002000

#define REG_SOC_LOPRI_LVLINT_CON_ADDR         0x40002010
#define BF_TDSP_INT00_FFSRAM0_CON_INFO        0x40002010, 0x00000100
#define BF_TDSP_INT01_FFSRAM1_CON_INFO        0x40002010, 0x00000101
#define BF_TDSP_INT02_FFSRAM2_CON_INFO        0x40002010, 0x00000102
#define BF_TDSP_INT03_QSPI_CON_INFO           0x40002010, 0x00000103
#define BF_TDSP_INT04_DTSYNC_CON_INFO         0x40002010, 0x00000104
#define BF_TDSP_INT05_DMA_CON_INFO            0x40002010, 0x00000105
#define BF_TDSP_INT06_AONIRQ1_CON_INFO        0x40002010, 0x00000106
#define BF_TDSP_INT07_AONIRQ2_CON_INFO        0x40002010, 0x00000107
#define BF_TDSP_INT08_AONIRQ3_CON_INFO        0x40002010, 0x00000108
#define BF_TDSP_INT09_AONIRQ4_CON_INFO        0x40002010, 0x00000109
#define BF_TDSP_INT10_MPIIRQ1_CON_INFO        0x40002010, 0x0000010A
#define BF_TDSP_INT11_MPIIRQ2_CON_INFO        0x40002010, 0x0000010B
#define BF_TDSP_INT12_MPIIRQ3_CON_INFO        0x40002010, 0x0000010C
#define BF_TDSP_INT13_UART_CON_INFO           0x40002010, 0x0000010D
#define BF_TDSP_INT14_SPI_CON_INFO            0x40002010, 0x0000010E
#define BF_TDSP_INT15_RSVD_INFO               0x40002010, 0x0000010F

#define REG_SOC_HIPRI_LVLINT_CON_ADDR         0x40002014
#define BF_TDSP_INT16_SEL_INFO                0x40002014, 0x00000400
#define BF_TDSP_INT17_SEL_INFO                0x40002014, 0x00000404
#define BF_TDSP_INT18_SEL_INFO                0x40002014, 0x00000408
#define BF_TDSP_INT19_SEL_INFO                0x40002014, 0x0000040C
#define BF_TDSP_INT20_SEL_INFO                0x40002014, 0x00000410
#define BF_TDSP_INT21_SEL_INFO                0x40002014, 0x00000414
#define BF_TDSP_INT22_SEL_INFO                0x40002014, 0x00000418
#define BF_TDSP_INT23_SEL_INFO                0x40002014, 0x0000041C

#define REG_SOC_LOPRI_EDGINT_CON_ADDR         0x40002018
#define BF_TDSP_INT24_GPT_CON_INFO            0x40002018, 0x00000118
#define BF_TDSP_INT25_WDT_CON_INFO            0x40002018, 0x00000119

#define REG_SOC_HIPRI_EDGINT_CON_ADDR         0x4000201C
#define BF_TDSP_INT26_SEL_INFO                0x4000201C, 0x00000400
#define BF_TDSP_INT27_SEL_INFO                0x4000201C, 0x00000404

#define REG_SOC_ERR_STATUS_ADDR               0x40002024
#define BF_TDSP_FATAL_ERROR_INFO              0x40002024, 0x00000100
#define BF_TDSP_DOUB_EXCP_SOC_ERR_STATUS_INFO 0x40002024, 0x00000101
#define BF_TDSP_WR_FDSPEQ_ERR_INFO            0x40002024, 0x00000108
#define BF_TDSP_WR_BUSY_ERR_INFO              0x40002024, 0x00000109

#define REG_SOC_PFAULT_INFO_ADDR              0x40002028
#define BF_TDSP_PFATAL_INFO_INFO              0x40002028, 0x00002000

#define REG_SOC_MEM_LIGHT_SLEEP_ADDR          0x40002040
#define BF_MEM_LIGHT_SLEEP_INFO               0x40002040, 0x00000900

#endif /* __ADI_LARK_BF_SOC_H__ */
/*! @} */
